/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the AttiDiAdesione service. Represents a row in the &quot;AQ_AttiDiAdesione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>servicebuilder.model.impl.AttiDiAdesioneModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>servicebuilder.model.impl.AttiDiAdesioneImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AttiDiAdesione
 * @generated
 */
@ProviderType
public interface AttiDiAdesioneModel extends BaseModel<AttiDiAdesione> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a atti di adesione model instance should use the {@link AttiDiAdesione} interface instead.
	 */

	/**
	 * Returns the primary key of this atti di adesione.
	 *
	 * @return the primary key of this atti di adesione
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this atti di adesione.
	 *
	 * @param primaryKey the primary key of this atti di adesione
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ atti di adesione of this atti di adesione.
	 *
	 * @return the id_ atti di adesione of this atti di adesione
	 */
	public long getId_AttiDiAdesione();

	/**
	 * Sets the id_ atti di adesione of this atti di adesione.
	 *
	 * @param Id_AttiDiAdesione the id_ atti di adesione of this atti di adesione
	 */
	public void setId_AttiDiAdesione(long Id_AttiDiAdesione);

	/**
	 * Returns the codice atto di adesione of this atti di adesione.
	 *
	 * @return the codice atto di adesione of this atti di adesione
	 */
	@AutoEscape
	public String getCodiceAttoDiAdesione();

	/**
	 * Sets the codice atto di adesione of this atti di adesione.
	 *
	 * @param CodiceAttoDiAdesione the codice atto di adesione of this atti di adesione
	 */
	public void setCodiceAttoDiAdesione(String CodiceAttoDiAdesione);

	/**
	 * Returns the fk_documenti of this atti di adesione.
	 *
	 * @return the fk_documenti of this atti di adesione
	 */
	public long getFK_documenti();

	/**
	 * Sets the fk_documenti of this atti di adesione.
	 *
	 * @param FK_documenti the fk_documenti of this atti di adesione
	 */
	public void setFK_documenti(long FK_documenti);

	/**
	 * Returns the fk_accordo quadro of this atti di adesione.
	 *
	 * @return the fk_accordo quadro of this atti di adesione
	 */
	public long getFK_accordoQuadro();

	/**
	 * Sets the fk_accordo quadro of this atti di adesione.
	 *
	 * @param FK_accordoQuadro the fk_accordo quadro of this atti di adesione
	 */
	public void setFK_accordoQuadro(long FK_accordoQuadro);

	/**
	 * Returns the anno of this atti di adesione.
	 *
	 * @return the anno of this atti di adesione
	 */
	public Integer getAnno();

	/**
	 * Sets the anno of this atti di adesione.
	 *
	 * @param Anno the anno of this atti di adesione
	 */
	public void setAnno(Integer Anno);

	/**
	 * Returns the stato of this atti di adesione.
	 *
	 * @return the stato of this atti di adesione
	 */
	@AutoEscape
	public String getStato();

	/**
	 * Sets the stato of this atti di adesione.
	 *
	 * @param Stato the stato of this atti di adesione
	 */
	public void setStato(String Stato);

	/**
	 * Returns the data stato of this atti di adesione.
	 *
	 * @return the data stato of this atti di adesione
	 */
	public Date getDataStato();

	/**
	 * Sets the data stato of this atti di adesione.
	 *
	 * @param DataStato the data stato of this atti di adesione
	 */
	public void setDataStato(Date DataStato);

	/**
	 * Returns the descrizione of this atti di adesione.
	 *
	 * @return the descrizione of this atti di adesione
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this atti di adesione.
	 *
	 * @param Descrizione the descrizione of this atti di adesione
	 */
	public void setDescrizione(String Descrizione);

	/**
	 * Returns the importo complessivo of this atti di adesione.
	 *
	 * @return the importo complessivo of this atti di adesione
	 */
	public Double getImportoComplessivo();

	/**
	 * Sets the importo complessivo of this atti di adesione.
	 *
	 * @param ImportoComplessivo the importo complessivo of this atti di adesione
	 */
	public void setImportoComplessivo(Double ImportoComplessivo);

	/**
	 * Returns the user ins of this atti di adesione.
	 *
	 * @return the user ins of this atti di adesione
	 */
	@AutoEscape
	public String getUserIns();

	/**
	 * Sets the user ins of this atti di adesione.
	 *
	 * @param userIns the user ins of this atti di adesione
	 */
	public void setUserIns(String userIns);

	/**
	 * Returns the user agg of this atti di adesione.
	 *
	 * @return the user agg of this atti di adesione
	 */
	@AutoEscape
	public String getUserAgg();

	/**
	 * Sets the user agg of this atti di adesione.
	 *
	 * @param userAgg the user agg of this atti di adesione
	 */
	public void setUserAgg(String userAgg);

	/**
	 * Returns the data ins of this atti di adesione.
	 *
	 * @return the data ins of this atti di adesione
	 */
	public Date getDataIns();

	/**
	 * Sets the data ins of this atti di adesione.
	 *
	 * @param dataIns the data ins of this atti di adesione
	 */
	public void setDataIns(Date dataIns);

	/**
	 * Returns the data agg of this atti di adesione.
	 *
	 * @return the data agg of this atti di adesione
	 */
	public Date getDataAgg();

	/**
	 * Sets the data agg of this atti di adesione.
	 *
	 * @param dataAgg the data agg of this atti di adesione
	 */
	public void setDataAgg(Date dataAgg);

	@Override
	public AttiDiAdesione cloneWithOriginalValues();

}