/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

import servicebuilder.service.persistence.ContrattiEsecutiviPK;

/**
 * The base model interface for the ContrattiEsecutivi service. Represents a row in the &quot;AQ_ContrattiEsecutivi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>servicebuilder.model.impl.ContrattiEsecutiviModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>servicebuilder.model.impl.ContrattiEsecutiviImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContrattiEsecutivi
 * @generated
 */
@ProviderType
public interface ContrattiEsecutiviModel extends BaseModel<ContrattiEsecutivi> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a contratti esecutivi model instance should use the {@link ContrattiEsecutivi} interface instead.
	 */

	/**
	 * Returns the primary key of this contratti esecutivi.
	 *
	 * @return the primary key of this contratti esecutivi
	 */
	public ContrattiEsecutiviPK getPrimaryKey();

	/**
	 * Sets the primary key of this contratti esecutivi.
	 *
	 * @param primaryKey the primary key of this contratti esecutivi
	 */
	public void setPrimaryKey(ContrattiEsecutiviPK primaryKey);

	/**
	 * Returns the codice contratto of this contratti esecutivi.
	 *
	 * @return the codice contratto of this contratti esecutivi
	 */
	@AutoEscape
	public String getCodiceContratto();

	/**
	 * Sets the codice contratto of this contratti esecutivi.
	 *
	 * @param CodiceContratto the codice contratto of this contratti esecutivi
	 */
	public void setCodiceContratto(String CodiceContratto);

	/**
	 * Returns the id_ contratti esecutivi of this contratti esecutivi.
	 *
	 * @return the id_ contratti esecutivi of this contratti esecutivi
	 */
	public long getId_ContrattiEsecutivi();

	/**
	 * Sets the id_ contratti esecutivi of this contratti esecutivi.
	 *
	 * @param Id_ContrattiEsecutivi the id_ contratti esecutivi of this contratti esecutivi
	 */
	public void setId_ContrattiEsecutivi(long Id_ContrattiEsecutivi);

	/**
	 * Returns the fk_documenti of this contratti esecutivi.
	 *
	 * @return the fk_documenti of this contratti esecutivi
	 */
	public long getFK_documenti();

	/**
	 * Sets the fk_documenti of this contratti esecutivi.
	 *
	 * @param FK_documenti the fk_documenti of this contratti esecutivi
	 */
	public void setFK_documenti(long FK_documenti);

	/**
	 * Returns the fk_progetti fabbisogni of this contratti esecutivi.
	 *
	 * @return the fk_progetti fabbisogni of this contratti esecutivi
	 */
	public long getFK_progettiFabbisogni();

	/**
	 * Sets the fk_progetti fabbisogni of this contratti esecutivi.
	 *
	 * @param FK_progettiFabbisogni the fk_progetti fabbisogni of this contratti esecutivi
	 */
	public void setFK_progettiFabbisogni(long FK_progettiFabbisogni);

	/**
	 * Returns the descrizione of this contratti esecutivi.
	 *
	 * @return the descrizione of this contratti esecutivi
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this contratti esecutivi.
	 *
	 * @param Descrizione the descrizione of this contratti esecutivi
	 */
	public void setDescrizione(String Descrizione);

	/**
	 * Returns the stato of this contratti esecutivi.
	 *
	 * @return the stato of this contratti esecutivi
	 */
	@AutoEscape
	public String getStato();

	/**
	 * Sets the stato of this contratti esecutivi.
	 *
	 * @param Stato the stato of this contratti esecutivi
	 */
	public void setStato(String Stato);

	/**
	 * Returns the data stato of this contratti esecutivi.
	 *
	 * @return the data stato of this contratti esecutivi
	 */
	public Date getDataStato();

	/**
	 * Sets the data stato of this contratti esecutivi.
	 *
	 * @param DataStato the data stato of this contratti esecutivi
	 */
	public void setDataStato(Date DataStato);

	/**
	 * Returns the data inizio contratto of this contratti esecutivi.
	 *
	 * @return the data inizio contratto of this contratti esecutivi
	 */
	public Date getDataInizioContratto();

	/**
	 * Sets the data inizio contratto of this contratti esecutivi.
	 *
	 * @param DataInizioContratto the data inizio contratto of this contratti esecutivi
	 */
	public void setDataInizioContratto(Date DataInizioContratto);

	/**
	 * Returns the data fine contratto of this contratti esecutivi.
	 *
	 * @return the data fine contratto of this contratti esecutivi
	 */
	public Date getDataFineContratto();

	/**
	 * Sets the data fine contratto of this contratti esecutivi.
	 *
	 * @param DataFineContratto the data fine contratto of this contratti esecutivi
	 */
	public void setDataFineContratto(Date DataFineContratto);

	/**
	 * Returns the importo complessivo of this contratti esecutivi.
	 *
	 * @return the importo complessivo of this contratti esecutivi
	 */
	public Double getImportoComplessivo();

	/**
	 * Sets the importo complessivo of this contratti esecutivi.
	 *
	 * @param ImportoComplessivo the importo complessivo of this contratti esecutivi
	 */
	public void setImportoComplessivo(Double ImportoComplessivo);

	/**
	 * Returns the user ins of this contratti esecutivi.
	 *
	 * @return the user ins of this contratti esecutivi
	 */
	@AutoEscape
	public String getUserIns();

	/**
	 * Sets the user ins of this contratti esecutivi.
	 *
	 * @param userIns the user ins of this contratti esecutivi
	 */
	public void setUserIns(String userIns);

	/**
	 * Returns the user agg of this contratti esecutivi.
	 *
	 * @return the user agg of this contratti esecutivi
	 */
	@AutoEscape
	public String getUserAgg();

	/**
	 * Sets the user agg of this contratti esecutivi.
	 *
	 * @param userAgg the user agg of this contratti esecutivi
	 */
	public void setUserAgg(String userAgg);

	/**
	 * Returns the data ins of this contratti esecutivi.
	 *
	 * @return the data ins of this contratti esecutivi
	 */
	public Date getDataIns();

	/**
	 * Sets the data ins of this contratti esecutivi.
	 *
	 * @param dataIns the data ins of this contratti esecutivi
	 */
	public void setDataIns(Date dataIns);

	/**
	 * Returns the data agg of this contratti esecutivi.
	 *
	 * @return the data agg of this contratti esecutivi
	 */
	public Date getDataAgg();

	/**
	 * Sets the data agg of this contratti esecutivi.
	 *
	 * @param dataAgg the data agg of this contratti esecutivi
	 */
	public void setDataAgg(Date dataAgg);

	@Override
	public ContrattiEsecutivi cloneWithOriginalValues();

}