/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model;

import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PianoStatoRel service. Represents a row in the &quot;AQ_PianoStatoRel&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>servicebuilder.model.impl.PianoStatoRelModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>servicebuilder.model.impl.PianoStatoRelImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PianoStatoRel
 * @generated
 */
@ProviderType
public interface PianoStatoRelModel extends BaseModel<PianoStatoRel> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a piano stato rel model instance should use the {@link PianoStatoRel} interface instead.
	 */

	/**
	 * Returns the primary key of this piano stato rel.
	 *
	 * @return the primary key of this piano stato rel
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this piano stato rel.
	 *
	 * @param primaryKey the primary key of this piano stato rel
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ relazione of this piano stato rel.
	 *
	 * @return the id_ relazione of this piano stato rel
	 */
	public long getId_Relazione();

	/**
	 * Sets the id_ relazione of this piano stato rel.
	 *
	 * @param Id_Relazione the id_ relazione of this piano stato rel
	 */
	public void setId_Relazione(long Id_Relazione);

	/**
	 * Returns the id_ pianodi lavoro of this piano stato rel.
	 *
	 * @return the id_ pianodi lavoro of this piano stato rel
	 */
	public long getId_PianodiLavoro();

	/**
	 * Sets the id_ pianodi lavoro of this piano stato rel.
	 *
	 * @param Id_PianodiLavoro the id_ pianodi lavoro of this piano stato rel
	 */
	public void setId_PianodiLavoro(long Id_PianodiLavoro);

	/**
	 * Returns the id_sal of this piano stato rel.
	 *
	 * @return the id_sal of this piano stato rel
	 */
	public long getId_SAL();

	/**
	 * Sets the id_sal of this piano stato rel.
	 *
	 * @param Id_SAL the id_sal of this piano stato rel
	 */
	public void setId_SAL(long Id_SAL);

	@Override
	public PianoStatoRel cloneWithOriginalValues();

}