/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PianiSubentro service. Represents a row in the &quot;AQ_PianiSubentro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>servicebuilder.model.impl.PianiSubentroModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>servicebuilder.model.impl.PianiSubentroImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PianiSubentro
 * @generated
 */
@ProviderType
public interface PianiSubentroModel extends BaseModel<PianiSubentro> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a piani subentro model instance should use the {@link PianiSubentro} interface instead.
	 */

	/**
	 * Returns the primary key of this piani subentro.
	 *
	 * @return the primary key of this piani subentro
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this piani subentro.
	 *
	 * @param primaryKey the primary key of this piani subentro
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ piani subentro of this piani subentro.
	 *
	 * @return the id_ piani subentro of this piani subentro
	 */
	public long getId_PianiSubentro();

	/**
	 * Sets the id_ piani subentro of this piani subentro.
	 *
	 * @param Id_PianiSubentro the id_ piani subentro of this piani subentro
	 */
	public void setId_PianiSubentro(long Id_PianiSubentro);

	/**
	 * Returns the codice piani di subentro of this piani subentro.
	 *
	 * @return the codice piani di subentro of this piani subentro
	 */
	@AutoEscape
	public String getCodicePianiDiSubentro();

	/**
	 * Sets the codice piani di subentro of this piani subentro.
	 *
	 * @param CodicePianiDiSubentro the codice piani di subentro of this piani subentro
	 */
	public void setCodicePianiDiSubentro(String CodicePianiDiSubentro);

	/**
	 * Returns the fk_documenti of this piani subentro.
	 *
	 * @return the fk_documenti of this piani subentro
	 */
	public long getFK_documenti();

	/**
	 * Sets the fk_documenti of this piani subentro.
	 *
	 * @param FK_documenti the fk_documenti of this piani subentro
	 */
	public void setFK_documenti(long FK_documenti);

	/**
	 * Returns the fk_accordo quadro of this piani subentro.
	 *
	 * @return the fk_accordo quadro of this piani subentro
	 */
	public long getFK_accordoQuadro();

	/**
	 * Sets the fk_accordo quadro of this piani subentro.
	 *
	 * @param FK_accordoQuadro the fk_accordo quadro of this piani subentro
	 */
	public void setFK_accordoQuadro(long FK_accordoQuadro);

	/**
	 * Returns the descrizione of this piani subentro.
	 *
	 * @return the descrizione of this piani subentro
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this piani subentro.
	 *
	 * @param Descrizione the descrizione of this piani subentro
	 */
	public void setDescrizione(String Descrizione);

	/**
	 * Returns the data inizio piano of this piani subentro.
	 *
	 * @return the data inizio piano of this piani subentro
	 */
	public Date getDataInizioPiano();

	/**
	 * Sets the data inizio piano of this piani subentro.
	 *
	 * @param DataInizioPiano the data inizio piano of this piani subentro
	 */
	public void setDataInizioPiano(Date DataInizioPiano);

	/**
	 * Returns the data fine piano of this piani subentro.
	 *
	 * @return the data fine piano of this piani subentro
	 */
	public Date getDataFinePiano();

	/**
	 * Sets the data fine piano of this piani subentro.
	 *
	 * @param DataFinePiano the data fine piano of this piani subentro
	 */
	public void setDataFinePiano(Date DataFinePiano);

	/**
	 * Returns the user ins of this piani subentro.
	 *
	 * @return the user ins of this piani subentro
	 */
	@AutoEscape
	public String getUserIns();

	/**
	 * Sets the user ins of this piani subentro.
	 *
	 * @param userIns the user ins of this piani subentro
	 */
	public void setUserIns(String userIns);

	/**
	 * Returns the user agg of this piani subentro.
	 *
	 * @return the user agg of this piani subentro
	 */
	@AutoEscape
	public String getUserAgg();

	/**
	 * Sets the user agg of this piani subentro.
	 *
	 * @param userAgg the user agg of this piani subentro
	 */
	public void setUserAgg(String userAgg);

	/**
	 * Returns the data ins of this piani subentro.
	 *
	 * @return the data ins of this piani subentro
	 */
	public Date getDataIns();

	/**
	 * Sets the data ins of this piani subentro.
	 *
	 * @param dataIns the data ins of this piani subentro
	 */
	public void setDataIns(Date dataIns);

	/**
	 * Returns the data agg of this piani subentro.
	 *
	 * @return the data agg of this piani subentro
	 */
	public Date getDataAgg();

	/**
	 * Sets the data agg of this piani subentro.
	 *
	 * @param dataAgg the data agg of this piani subentro
	 */
	public void setDataAgg(Date dataAgg);

	@Override
	public PianiSubentro cloneWithOriginalValues();

}