/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the PianiDiLavoroObiettivo service. Represents a row in the &quot;AQ_PianiDiLavoroObiettivo&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>servicebuilder.model.impl.PianiDiLavoroObiettivoModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>servicebuilder.model.impl.PianiDiLavoroObiettivoImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PianiDiLavoroObiettivo
 * @generated
 */
@ProviderType
public interface PianiDiLavoroObiettivoModel
	extends BaseModel<PianiDiLavoroObiettivo> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a piani di lavoro obiettivo model instance should use the {@link PianiDiLavoroObiettivo} interface instead.
	 */

	/**
	 * Returns the primary key of this piani di lavoro obiettivo.
	 *
	 * @return the primary key of this piani di lavoro obiettivo
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this piani di lavoro obiettivo.
	 *
	 * @param primaryKey the primary key of this piani di lavoro obiettivo
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ piano di lavoro of this piani di lavoro obiettivo.
	 *
	 * @return the id_ piano di lavoro of this piani di lavoro obiettivo
	 */
	public long getId_PianoDiLavoro();

	/**
	 * Sets the id_ piano di lavoro of this piani di lavoro obiettivo.
	 *
	 * @param Id_PianoDiLavoro the id_ piano di lavoro of this piani di lavoro obiettivo
	 */
	public void setId_PianoDiLavoro(long Id_PianoDiLavoro);

	/**
	 * Returns the codice piano lavoro obiettivo of this piani di lavoro obiettivo.
	 *
	 * @return the codice piano lavoro obiettivo of this piani di lavoro obiettivo
	 */
	@AutoEscape
	public String getCodicePianoLavoroObiettivo();

	/**
	 * Sets the codice piano lavoro obiettivo of this piani di lavoro obiettivo.
	 *
	 * @param CodicePianoLavoroObiettivo the codice piano lavoro obiettivo of this piani di lavoro obiettivo
	 */
	public void setCodicePianoLavoroObiettivo(
		String CodicePianoLavoroObiettivo);

	/**
	 * Returns the fk_documenti of this piani di lavoro obiettivo.
	 *
	 * @return the fk_documenti of this piani di lavoro obiettivo
	 */
	public long getFK_documenti();

	/**
	 * Sets the fk_documenti of this piani di lavoro obiettivo.
	 *
	 * @param FK_documenti the fk_documenti of this piani di lavoro obiettivo
	 */
	public void setFK_documenti(long FK_documenti);

	/**
	 * Returns the fk_progetti fabbisogni of this piani di lavoro obiettivo.
	 *
	 * @return the fk_progetti fabbisogni of this piani di lavoro obiettivo
	 */
	public long getFK_progettiFabbisogni();

	/**
	 * Sets the fk_progetti fabbisogni of this piani di lavoro obiettivo.
	 *
	 * @param FK_progettiFabbisogni the fk_progetti fabbisogni of this piani di lavoro obiettivo
	 */
	public void setFK_progettiFabbisogni(long FK_progettiFabbisogni);

	/**
	 * Returns the descrizione of this piani di lavoro obiettivo.
	 *
	 * @return the descrizione of this piani di lavoro obiettivo
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this piani di lavoro obiettivo.
	 *
	 * @param Descrizione the descrizione of this piani di lavoro obiettivo
	 */
	public void setDescrizione(String Descrizione);

	/**
	 * Returns the data inizio piano of this piani di lavoro obiettivo.
	 *
	 * @return the data inizio piano of this piani di lavoro obiettivo
	 */
	public Date getDataInizioPiano();

	/**
	 * Sets the data inizio piano of this piani di lavoro obiettivo.
	 *
	 * @param DataInizioPiano the data inizio piano of this piani di lavoro obiettivo
	 */
	public void setDataInizioPiano(Date DataInizioPiano);

	/**
	 * Returns the data fine piano of this piani di lavoro obiettivo.
	 *
	 * @return the data fine piano of this piani di lavoro obiettivo
	 */
	public Date getDataFinePiano();

	/**
	 * Sets the data fine piano of this piani di lavoro obiettivo.
	 *
	 * @param DataFinePiano the data fine piano of this piani di lavoro obiettivo
	 */
	public void setDataFinePiano(Date DataFinePiano);

	/**
	 * Returns the importo complessivo of this piani di lavoro obiettivo.
	 *
	 * @return the importo complessivo of this piani di lavoro obiettivo
	 */
	public Double getImportoComplessivo();

	/**
	 * Sets the importo complessivo of this piani di lavoro obiettivo.
	 *
	 * @param ImportoComplessivo the importo complessivo of this piani di lavoro obiettivo
	 */
	public void setImportoComplessivo(Double ImportoComplessivo);

	/**
	 * Returns the user ins of this piani di lavoro obiettivo.
	 *
	 * @return the user ins of this piani di lavoro obiettivo
	 */
	@AutoEscape
	public String getUserIns();

	/**
	 * Sets the user ins of this piani di lavoro obiettivo.
	 *
	 * @param userIns the user ins of this piani di lavoro obiettivo
	 */
	public void setUserIns(String userIns);

	/**
	 * Returns the user agg of this piani di lavoro obiettivo.
	 *
	 * @return the user agg of this piani di lavoro obiettivo
	 */
	@AutoEscape
	public String getUserAgg();

	/**
	 * Sets the user agg of this piani di lavoro obiettivo.
	 *
	 * @param userAgg the user agg of this piani di lavoro obiettivo
	 */
	public void setUserAgg(String userAgg);

	/**
	 * Returns the data ins of this piani di lavoro obiettivo.
	 *
	 * @return the data ins of this piani di lavoro obiettivo
	 */
	public Date getDataIns();

	/**
	 * Sets the data ins of this piani di lavoro obiettivo.
	 *
	 * @param dataIns the data ins of this piani di lavoro obiettivo
	 */
	public void setDataIns(Date dataIns);

	/**
	 * Returns the data agg of this piani di lavoro obiettivo.
	 *
	 * @return the data agg of this piani di lavoro obiettivo
	 */
	public Date getDataAgg();

	/**
	 * Sets the data agg of this piani di lavoro obiettivo.
	 *
	 * @param dataAgg the data agg of this piani di lavoro obiettivo
	 */
	public void setDataAgg(Date dataAgg);

	@Override
	public PianiDiLavoroObiettivo cloneWithOriginalValues();

}