/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProgettiFabbisogni service. Represents a row in the &quot;AQ_ProgettiFabbisogni&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>servicebuilder.model.impl.ProgettiFabbisogniModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>servicebuilder.model.impl.ProgettiFabbisogniImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProgettiFabbisogni
 * @generated
 */
@ProviderType
public interface ProgettiFabbisogniModel extends BaseModel<ProgettiFabbisogni> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a progetti fabbisogni model instance should use the {@link ProgettiFabbisogni} interface instead.
	 */

	/**
	 * Returns the primary key of this progetti fabbisogni.
	 *
	 * @return the primary key of this progetti fabbisogni
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this progetti fabbisogni.
	 *
	 * @param primaryKey the primary key of this progetti fabbisogni
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_ progetti fabbisogni of this progetti fabbisogni.
	 *
	 * @return the id_ progetti fabbisogni of this progetti fabbisogni
	 */
	public long getId_ProgettiFabbisogni();

	/**
	 * Sets the id_ progetti fabbisogni of this progetti fabbisogni.
	 *
	 * @param Id_ProgettiFabbisogni the id_ progetti fabbisogni of this progetti fabbisogni
	 */
	public void setId_ProgettiFabbisogni(long Id_ProgettiFabbisogni);

	/**
	 * Returns the codice fabbisogni of this progetti fabbisogni.
	 *
	 * @return the codice fabbisogni of this progetti fabbisogni
	 */
	@AutoEscape
	public String getCodiceFabbisogni();

	/**
	 * Sets the codice fabbisogni of this progetti fabbisogni.
	 *
	 * @param CodiceFabbisogni the codice fabbisogni of this progetti fabbisogni
	 */
	public void setCodiceFabbisogni(String CodiceFabbisogni);

	/**
	 * Returns the fk_documenti of this progetti fabbisogni.
	 *
	 * @return the fk_documenti of this progetti fabbisogni
	 */
	public long getFK_documenti();

	/**
	 * Sets the fk_documenti of this progetti fabbisogni.
	 *
	 * @param FK_documenti the fk_documenti of this progetti fabbisogni
	 */
	public void setFK_documenti(long FK_documenti);

	/**
	 * Returns the fk_progetti fabbisogni of this progetti fabbisogni.
	 *
	 * @return the fk_progetti fabbisogni of this progetti fabbisogni
	 */
	public long getFK_progettiFabbisogni();

	/**
	 * Sets the fk_progetti fabbisogni of this progetti fabbisogni.
	 *
	 * @param FK_progettiFabbisogni the fk_progetti fabbisogni of this progetti fabbisogni
	 */
	public void setFK_progettiFabbisogni(long FK_progettiFabbisogni);

	/**
	 * Returns the fk_piani fabbisogni of this progetti fabbisogni.
	 *
	 * @return the fk_piani fabbisogni of this progetti fabbisogni
	 */
	public long getFK_pianiFabbisogni();

	/**
	 * Sets the fk_piani fabbisogni of this progetti fabbisogni.
	 *
	 * @param FK_pianiFabbisogni the fk_piani fabbisogni of this progetti fabbisogni
	 */
	public void setFK_pianiFabbisogni(long FK_pianiFabbisogni);

	/**
	 * Returns the stato of this progetti fabbisogni.
	 *
	 * @return the stato of this progetti fabbisogni
	 */
	@AutoEscape
	public String getStato();

	/**
	 * Sets the stato of this progetti fabbisogni.
	 *
	 * @param Stato the stato of this progetti fabbisogni
	 */
	public void setStato(String Stato);

	/**
	 * Returns the data stato of this progetti fabbisogni.
	 *
	 * @return the data stato of this progetti fabbisogni
	 */
	public Date getDataStato();

	/**
	 * Sets the data stato of this progetti fabbisogni.
	 *
	 * @param DataStato the data stato of this progetti fabbisogni
	 */
	public void setDataStato(Date DataStato);

	/**
	 * Returns the descrizione of this progetti fabbisogni.
	 *
	 * @return the descrizione of this progetti fabbisogni
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this progetti fabbisogni.
	 *
	 * @param Descrizione the descrizione of this progetti fabbisogni
	 */
	public void setDescrizione(String Descrizione);

	/**
	 * Returns the data scadenza of this progetti fabbisogni.
	 *
	 * @return the data scadenza of this progetti fabbisogni
	 */
	public Date getDataScadenza();

	/**
	 * Sets the data scadenza of this progetti fabbisogni.
	 *
	 * @param DataScadenza the data scadenza of this progetti fabbisogni
	 */
	public void setDataScadenza(Date DataScadenza);

	/**
	 * Returns the importo complessivo of this progetti fabbisogni.
	 *
	 * @return the importo complessivo of this progetti fabbisogni
	 */
	public Double getImportoComplessivo();

	/**
	 * Sets the importo complessivo of this progetti fabbisogni.
	 *
	 * @param ImportoComplessivo the importo complessivo of this progetti fabbisogni
	 */
	public void setImportoComplessivo(Double ImportoComplessivo);

	/**
	 * Returns the data inizio piano of this progetti fabbisogni.
	 *
	 * @return the data inizio piano of this progetti fabbisogni
	 */
	public Date getDataInizioPiano();

	/**
	 * Sets the data inizio piano of this progetti fabbisogni.
	 *
	 * @param DataInizioPiano the data inizio piano of this progetti fabbisogni
	 */
	public void setDataInizioPiano(Date DataInizioPiano);

	/**
	 * Returns the data fine piano of this progetti fabbisogni.
	 *
	 * @return the data fine piano of this progetti fabbisogni
	 */
	public Date getDataFinePiano();

	/**
	 * Sets the data fine piano of this progetti fabbisogni.
	 *
	 * @param DataFinePiano the data fine piano of this progetti fabbisogni
	 */
	public void setDataFinePiano(Date DataFinePiano);

	/**
	 * Returns the user ins of this progetti fabbisogni.
	 *
	 * @return the user ins of this progetti fabbisogni
	 */
	@AutoEscape
	public String getUserIns();

	/**
	 * Sets the user ins of this progetti fabbisogni.
	 *
	 * @param userIns the user ins of this progetti fabbisogni
	 */
	public void setUserIns(String userIns);

	/**
	 * Returns the user agg of this progetti fabbisogni.
	 *
	 * @return the user agg of this progetti fabbisogni
	 */
	@AutoEscape
	public String getUserAgg();

	/**
	 * Sets the user agg of this progetti fabbisogni.
	 *
	 * @param userAgg the user agg of this progetti fabbisogni
	 */
	public void setUserAgg(String userAgg);

	/**
	 * Returns the data ins of this progetti fabbisogni.
	 *
	 * @return the data ins of this progetti fabbisogni
	 */
	public Date getDataIns();

	/**
	 * Sets the data ins of this progetti fabbisogni.
	 *
	 * @param dataIns the data ins of this progetti fabbisogni
	 */
	public void setDataIns(Date dataIns);

	/**
	 * Returns the data agg of this progetti fabbisogni.
	 *
	 * @return the data agg of this progetti fabbisogni
	 */
	public Date getDataAgg();

	/**
	 * Sets the data agg of this progetti fabbisogni.
	 *
	 * @param dataAgg the data agg of this progetti fabbisogni
	 */
	public void setDataAgg(Date dataAgg);

	@Override
	public ProgettiFabbisogni cloneWithOriginalValues();

}