/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the StatoAvanzamentoLavori service. Represents a row in the &quot;AQ_StatoAvanzamentoLavori&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>servicebuilder.model.impl.StatoAvanzamentoLavoriModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>servicebuilder.model.impl.StatoAvanzamentoLavoriImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see StatoAvanzamentoLavori
 * @generated
 */
@ProviderType
public interface StatoAvanzamentoLavoriModel
	extends BaseModel<StatoAvanzamentoLavori> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a stato avanzamento lavori model instance should use the {@link StatoAvanzamentoLavori} interface instead.
	 */

	/**
	 * Returns the primary key of this stato avanzamento lavori.
	 *
	 * @return the primary key of this stato avanzamento lavori
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this stato avanzamento lavori.
	 *
	 * @param primaryKey the primary key of this stato avanzamento lavori
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id_sal of this stato avanzamento lavori.
	 *
	 * @return the id_sal of this stato avanzamento lavori
	 */
	public long getId_SAL();

	/**
	 * Sets the id_sal of this stato avanzamento lavori.
	 *
	 * @param Id_SAL the id_sal of this stato avanzamento lavori
	 */
	public void setId_SAL(long Id_SAL);

	/**
	 * Returns the fk_documenti of this stato avanzamento lavori.
	 *
	 * @return the fk_documenti of this stato avanzamento lavori
	 */
	public long getFK_documenti();

	/**
	 * Sets the fk_documenti of this stato avanzamento lavori.
	 *
	 * @param FK_documenti the fk_documenti of this stato avanzamento lavori
	 */
	public void setFK_documenti(long FK_documenti);

	/**
	 * Returns the codice sal of this stato avanzamento lavori.
	 *
	 * @return the codice sal of this stato avanzamento lavori
	 */
	@AutoEscape
	public String getCodiceSAL();

	/**
	 * Sets the codice sal of this stato avanzamento lavori.
	 *
	 * @param CodiceSAL the codice sal of this stato avanzamento lavori
	 */
	public void setCodiceSAL(String CodiceSAL);

	/**
	 * Returns the descrizione of this stato avanzamento lavori.
	 *
	 * @return the descrizione of this stato avanzamento lavori
	 */
	@AutoEscape
	public String getDescrizione();

	/**
	 * Sets the descrizione of this stato avanzamento lavori.
	 *
	 * @param Descrizione the descrizione of this stato avanzamento lavori
	 */
	public void setDescrizione(String Descrizione);

	/**
	 * Returns the stato of this stato avanzamento lavori.
	 *
	 * @return the stato of this stato avanzamento lavori
	 */
	@AutoEscape
	public String getStato();

	/**
	 * Sets the stato of this stato avanzamento lavori.
	 *
	 * @param Stato the stato of this stato avanzamento lavori
	 */
	public void setStato(String Stato);

	/**
	 * Returns the data stato of this stato avanzamento lavori.
	 *
	 * @return the data stato of this stato avanzamento lavori
	 */
	public Date getDataStato();

	/**
	 * Sets the data stato of this stato avanzamento lavori.
	 *
	 * @param DataStato the data stato of this stato avanzamento lavori
	 */
	public void setDataStato(Date DataStato);

	/**
	 * Returns the mese anno riferimento of this stato avanzamento lavori.
	 *
	 * @return the mese anno riferimento of this stato avanzamento lavori
	 */
	@AutoEscape
	public String getMeseAnnoRiferimento();

	/**
	 * Sets the mese anno riferimento of this stato avanzamento lavori.
	 *
	 * @param MeseAnnoRiferimento the mese anno riferimento of this stato avanzamento lavori
	 */
	public void setMeseAnnoRiferimento(String MeseAnnoRiferimento);

	/**
	 * Returns the importo complessivo of this stato avanzamento lavori.
	 *
	 * @return the importo complessivo of this stato avanzamento lavori
	 */
	public Double getImportoComplessivo();

	/**
	 * Sets the importo complessivo of this stato avanzamento lavori.
	 *
	 * @param ImportoComplessivo the importo complessivo of this stato avanzamento lavori
	 */
	public void setImportoComplessivo(Double ImportoComplessivo);

	/**
	 * Returns the user ins of this stato avanzamento lavori.
	 *
	 * @return the user ins of this stato avanzamento lavori
	 */
	@AutoEscape
	public String getUserIns();

	/**
	 * Sets the user ins of this stato avanzamento lavori.
	 *
	 * @param userIns the user ins of this stato avanzamento lavori
	 */
	public void setUserIns(String userIns);

	/**
	 * Returns the user agg of this stato avanzamento lavori.
	 *
	 * @return the user agg of this stato avanzamento lavori
	 */
	@AutoEscape
	public String getUserAgg();

	/**
	 * Sets the user agg of this stato avanzamento lavori.
	 *
	 * @param userAgg the user agg of this stato avanzamento lavori
	 */
	public void setUserAgg(String userAgg);

	/**
	 * Returns the data ins of this stato avanzamento lavori.
	 *
	 * @return the data ins of this stato avanzamento lavori
	 */
	public Date getDataIns();

	/**
	 * Sets the data ins of this stato avanzamento lavori.
	 *
	 * @param dataIns the data ins of this stato avanzamento lavori
	 */
	public void setDataIns(Date dataIns);

	/**
	 * Returns the data agg of this stato avanzamento lavori.
	 *
	 * @return the data agg of this stato avanzamento lavori
	 */
	public Date getDataAgg();

	/**
	 * Sets the data agg of this stato avanzamento lavori.
	 *
	 * @param dataAgg the data agg of this stato avanzamento lavori
	 */
	public void setDataAgg(Date dataAgg);

	@Override
	public StatoAvanzamentoLavori cloneWithOriginalValues();

}