/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import servicebuilder.model.PianoStatoRel;

import servicebuilder.service.PianoStatoRelLocalService;
import servicebuilder.service.PianoStatoRelLocalServiceUtil;
import servicebuilder.service.persistence.AccordoQuadroPersistence;
import servicebuilder.service.persistence.AttiDiAdesionePersistence;
import servicebuilder.service.persistence.ContrattiEsecutiviPersistence;
import servicebuilder.service.persistence.DocumentiPersistence;
import servicebuilder.service.persistence.PianiDeiRischiPersistence;
import servicebuilder.service.persistence.PianiDiLavoroObiettivoPersistence;
import servicebuilder.service.persistence.PianiDiQualitaPersistence;
import servicebuilder.service.persistence.PianiFabbisogniPersistence;
import servicebuilder.service.persistence.PianiSubentroPersistence;
import servicebuilder.service.persistence.PianoStatoRelPersistence;
import servicebuilder.service.persistence.ProgettiFabbisogniPersistence;
import servicebuilder.service.persistence.StatoAvanzamentoLavoriPersistence;

/**
 * Provides the base implementation for the piano stato rel local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link servicebuilder.service.impl.PianoStatoRelLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see servicebuilder.service.impl.PianoStatoRelLocalServiceImpl
 * @generated
 */
public abstract class PianoStatoRelLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, PianoStatoRelLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>PianoStatoRelLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>PianoStatoRelLocalServiceUtil</code>.
	 */

	/**
	 * Adds the piano stato rel to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PianoStatoRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param pianoStatoRel the piano stato rel
	 * @return the piano stato rel that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PianoStatoRel addPianoStatoRel(PianoStatoRel pianoStatoRel) {
		pianoStatoRel.setNew(true);

		return pianoStatoRelPersistence.update(pianoStatoRel);
	}

	/**
	 * Creates a new piano stato rel with the primary key. Does not add the piano stato rel to the database.
	 *
	 * @param Id_Relazione the primary key for the new piano stato rel
	 * @return the new piano stato rel
	 */
	@Override
	@Transactional(enabled = false)
	public PianoStatoRel createPianoStatoRel(long Id_Relazione) {
		return pianoStatoRelPersistence.create(Id_Relazione);
	}

	/**
	 * Deletes the piano stato rel with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PianoStatoRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param Id_Relazione the primary key of the piano stato rel
	 * @return the piano stato rel that was removed
	 * @throws PortalException if a piano stato rel with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PianoStatoRel deletePianoStatoRel(long Id_Relazione)
		throws PortalException {

		return pianoStatoRelPersistence.remove(Id_Relazione);
	}

	/**
	 * Deletes the piano stato rel from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PianoStatoRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param pianoStatoRel the piano stato rel
	 * @return the piano stato rel that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public PianoStatoRel deletePianoStatoRel(PianoStatoRel pianoStatoRel) {
		return pianoStatoRelPersistence.remove(pianoStatoRel);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return pianoStatoRelPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			PianoStatoRel.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return pianoStatoRelPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>servicebuilder.model.impl.PianoStatoRelModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return pianoStatoRelPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>servicebuilder.model.impl.PianoStatoRelModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return pianoStatoRelPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return pianoStatoRelPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return pianoStatoRelPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public PianoStatoRel fetchPianoStatoRel(long Id_Relazione) {
		return pianoStatoRelPersistence.fetchByPrimaryKey(Id_Relazione);
	}

	/**
	 * Returns the piano stato rel with the primary key.
	 *
	 * @param Id_Relazione the primary key of the piano stato rel
	 * @return the piano stato rel
	 * @throws PortalException if a piano stato rel with the primary key could not be found
	 */
	@Override
	public PianoStatoRel getPianoStatoRel(long Id_Relazione)
		throws PortalException {

		return pianoStatoRelPersistence.findByPrimaryKey(Id_Relazione);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(pianoStatoRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PianoStatoRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("Id_Relazione");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			pianoStatoRelLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(PianoStatoRel.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"Id_Relazione");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(pianoStatoRelLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(PianoStatoRel.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("Id_Relazione");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return pianoStatoRelPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return pianoStatoRelLocalService.deletePianoStatoRel(
			(PianoStatoRel)persistedModel);
	}

	@Override
	public BasePersistence<PianoStatoRel> getBasePersistence() {
		return pianoStatoRelPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return pianoStatoRelPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the piano stato rels.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>servicebuilder.model.impl.PianoStatoRelModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of piano stato rels
	 * @param end the upper bound of the range of piano stato rels (not inclusive)
	 * @return the range of piano stato rels
	 */
	@Override
	public List<PianoStatoRel> getPianoStatoRels(int start, int end) {
		return pianoStatoRelPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of piano stato rels.
	 *
	 * @return the number of piano stato rels
	 */
	@Override
	public int getPianoStatoRelsCount() {
		return pianoStatoRelPersistence.countAll();
	}

	/**
	 * Updates the piano stato rel in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect PianoStatoRelLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param pianoStatoRel the piano stato rel
	 * @return the piano stato rel that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public PianoStatoRel updatePianoStatoRel(PianoStatoRel pianoStatoRel) {
		return pianoStatoRelPersistence.update(pianoStatoRel);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			PianoStatoRelLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		pianoStatoRelLocalService = (PianoStatoRelLocalService)aopProxy;

		_setLocalServiceUtilService(pianoStatoRelLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return PianoStatoRelLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return PianoStatoRel.class;
	}

	protected String getModelClassName() {
		return PianoStatoRel.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = pianoStatoRelPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		PianoStatoRelLocalService pianoStatoRelLocalService) {

		try {
			Field field = PianoStatoRelLocalServiceUtil.class.getDeclaredField(
				"_service");

			field.setAccessible(true);

			field.set(null, pianoStatoRelLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AccordoQuadroPersistence accordoQuadroPersistence;

	@Reference
	protected AttiDiAdesionePersistence attiDiAdesionePersistence;

	@Reference
	protected ContrattiEsecutiviPersistence contrattiEsecutiviPersistence;

	@Reference
	protected DocumentiPersistence documentiPersistence;

	@Reference
	protected PianiDeiRischiPersistence pianiDeiRischiPersistence;

	@Reference
	protected PianiDiLavoroObiettivoPersistence
		pianiDiLavoroObiettivoPersistence;

	@Reference
	protected PianiDiQualitaPersistence pianiDiQualitaPersistence;

	@Reference
	protected PianiFabbisogniPersistence pianiFabbisogniPersistence;

	@Reference
	protected PianiSubentroPersistence pianiSubentroPersistence;

	protected PianoStatoRelLocalService pianoStatoRelLocalService;

	@Reference
	protected PianoStatoRelPersistence pianoStatoRelPersistence;

	@Reference
	protected ProgettiFabbisogniPersistence progettiFabbisogniPersistence;

	@Reference
	protected StatoAvanzamentoLavoriPersistence
		statoAvanzamentoLavoriPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}