/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.service.base;

import com.liferay.petra.sql.dsl.query.DSLQuery;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import java.io.Serializable;

import java.lang.reflect.Field;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Deactivate;
import org.osgi.service.component.annotations.Reference;

import servicebuilder.model.ProgettiFabbisogni;

import servicebuilder.service.ProgettiFabbisogniLocalService;
import servicebuilder.service.ProgettiFabbisogniLocalServiceUtil;
import servicebuilder.service.persistence.AccordoQuadroPersistence;
import servicebuilder.service.persistence.AttiDiAdesionePersistence;
import servicebuilder.service.persistence.ContrattiEsecutiviPersistence;
import servicebuilder.service.persistence.DocumentiPersistence;
import servicebuilder.service.persistence.PianiDeiRischiPersistence;
import servicebuilder.service.persistence.PianiDiLavoroObiettivoPersistence;
import servicebuilder.service.persistence.PianiDiQualitaPersistence;
import servicebuilder.service.persistence.PianiFabbisogniPersistence;
import servicebuilder.service.persistence.PianiSubentroPersistence;
import servicebuilder.service.persistence.PianoStatoRelPersistence;
import servicebuilder.service.persistence.ProgettiFabbisogniPersistence;
import servicebuilder.service.persistence.StatoAvanzamentoLavoriPersistence;

/**
 * Provides the base implementation for the progetti fabbisogni local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link servicebuilder.service.impl.ProgettiFabbisogniLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see servicebuilder.service.impl.ProgettiFabbisogniLocalServiceImpl
 * @generated
 */
public abstract class ProgettiFabbisogniLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   ProgettiFabbisogniLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>ProgettiFabbisogniLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>ProgettiFabbisogniLocalServiceUtil</code>.
	 */

	/**
	 * Adds the progetti fabbisogni to the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ProgettiFabbisogniLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param progettiFabbisogni the progetti fabbisogni
	 * @return the progetti fabbisogni that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ProgettiFabbisogni addProgettiFabbisogni(
		ProgettiFabbisogni progettiFabbisogni) {

		progettiFabbisogni.setNew(true);

		return progettiFabbisogniPersistence.update(progettiFabbisogni);
	}

	/**
	 * Creates a new progetti fabbisogni with the primary key. Does not add the progetti fabbisogni to the database.
	 *
	 * @param Id_ProgettiFabbisogni the primary key for the new progetti fabbisogni
	 * @return the new progetti fabbisogni
	 */
	@Override
	@Transactional(enabled = false)
	public ProgettiFabbisogni createProgettiFabbisogni(
		long Id_ProgettiFabbisogni) {

		return progettiFabbisogniPersistence.create(Id_ProgettiFabbisogni);
	}

	/**
	 * Deletes the progetti fabbisogni with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ProgettiFabbisogniLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param Id_ProgettiFabbisogni the primary key of the progetti fabbisogni
	 * @return the progetti fabbisogni that was removed
	 * @throws PortalException if a progetti fabbisogni with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ProgettiFabbisogni deleteProgettiFabbisogni(
			long Id_ProgettiFabbisogni)
		throws PortalException {

		return progettiFabbisogniPersistence.remove(Id_ProgettiFabbisogni);
	}

	/**
	 * Deletes the progetti fabbisogni from the database. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ProgettiFabbisogniLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param progettiFabbisogni the progetti fabbisogni
	 * @return the progetti fabbisogni that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public ProgettiFabbisogni deleteProgettiFabbisogni(
		ProgettiFabbisogni progettiFabbisogni) {

		return progettiFabbisogniPersistence.remove(progettiFabbisogni);
	}

	@Override
	public <T> T dslQuery(DSLQuery dslQuery) {
		return progettiFabbisogniPersistence.dslQuery(dslQuery);
	}

	@Override
	public int dslQueryCount(DSLQuery dslQuery) {
		Long count = dslQuery(dslQuery);

		return count.intValue();
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			ProgettiFabbisogni.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return progettiFabbisogniPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>servicebuilder.model.impl.ProgettiFabbisogniModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return progettiFabbisogniPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>servicebuilder.model.impl.ProgettiFabbisogniModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return progettiFabbisogniPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return progettiFabbisogniPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return progettiFabbisogniPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public ProgettiFabbisogni fetchProgettiFabbisogni(
		long Id_ProgettiFabbisogni) {

		return progettiFabbisogniPersistence.fetchByPrimaryKey(
			Id_ProgettiFabbisogni);
	}

	/**
	 * Returns the progetti fabbisogni with the primary key.
	 *
	 * @param Id_ProgettiFabbisogni the primary key of the progetti fabbisogni
	 * @return the progetti fabbisogni
	 * @throws PortalException if a progetti fabbisogni with the primary key could not be found
	 */
	@Override
	public ProgettiFabbisogni getProgettiFabbisogni(long Id_ProgettiFabbisogni)
		throws PortalException {

		return progettiFabbisogniPersistence.findByPrimaryKey(
			Id_ProgettiFabbisogni);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			progettiFabbisogniLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ProgettiFabbisogni.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"Id_ProgettiFabbisogni");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			progettiFabbisogniLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(ProgettiFabbisogni.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"Id_ProgettiFabbisogni");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			progettiFabbisogniLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(ProgettiFabbisogni.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"Id_ProgettiFabbisogni");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel createPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return progettiFabbisogniPersistence.create(
			((Long)primaryKeyObj).longValue());
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return progettiFabbisogniLocalService.deleteProgettiFabbisogni(
			(ProgettiFabbisogni)persistedModel);
	}

	@Override
	public BasePersistence<ProgettiFabbisogni> getBasePersistence() {
		return progettiFabbisogniPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return progettiFabbisogniPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the progetti fabbisognis.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>servicebuilder.model.impl.ProgettiFabbisogniModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of progetti fabbisognis
	 * @param end the upper bound of the range of progetti fabbisognis (not inclusive)
	 * @return the range of progetti fabbisognis
	 */
	@Override
	public List<ProgettiFabbisogni> getProgettiFabbisognis(int start, int end) {
		return progettiFabbisogniPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of progetti fabbisognis.
	 *
	 * @return the number of progetti fabbisognis
	 */
	@Override
	public int getProgettiFabbisognisCount() {
		return progettiFabbisogniPersistence.countAll();
	}

	/**
	 * Updates the progetti fabbisogni in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * <p>
	 * <strong>Important:</strong> Inspect ProgettiFabbisogniLocalServiceImpl for overloaded versions of the method. If provided, use these entry points to the API, as the implementation logic may require the additional parameters defined there.
	 * </p>
	 *
	 * @param progettiFabbisogni the progetti fabbisogni
	 * @return the progetti fabbisogni that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public ProgettiFabbisogni updateProgettiFabbisogni(
		ProgettiFabbisogni progettiFabbisogni) {

		return progettiFabbisogniPersistence.update(progettiFabbisogni);
	}

	@Deactivate
	protected void deactivate() {
		_setLocalServiceUtilService(null);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			ProgettiFabbisogniLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		progettiFabbisogniLocalService =
			(ProgettiFabbisogniLocalService)aopProxy;

		_setLocalServiceUtilService(progettiFabbisogniLocalService);
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return ProgettiFabbisogniLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return ProgettiFabbisogni.class;
	}

	protected String getModelClassName() {
		return ProgettiFabbisogni.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				progettiFabbisogniPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	private void _setLocalServiceUtilService(
		ProgettiFabbisogniLocalService progettiFabbisogniLocalService) {

		try {
			Field field =
				ProgettiFabbisogniLocalServiceUtil.class.getDeclaredField(
					"_service");

			field.setAccessible(true);

			field.set(null, progettiFabbisogniLocalService);
		}
		catch (ReflectiveOperationException reflectiveOperationException) {
			throw new RuntimeException(reflectiveOperationException);
		}
	}

	@Reference
	protected AccordoQuadroPersistence accordoQuadroPersistence;

	@Reference
	protected AttiDiAdesionePersistence attiDiAdesionePersistence;

	@Reference
	protected ContrattiEsecutiviPersistence contrattiEsecutiviPersistence;

	@Reference
	protected DocumentiPersistence documentiPersistence;

	@Reference
	protected PianiDeiRischiPersistence pianiDeiRischiPersistence;

	@Reference
	protected PianiDiLavoroObiettivoPersistence
		pianiDiLavoroObiettivoPersistence;

	@Reference
	protected PianiDiQualitaPersistence pianiDiQualitaPersistence;

	@Reference
	protected PianiFabbisogniPersistence pianiFabbisogniPersistence;

	@Reference
	protected PianiSubentroPersistence pianiSubentroPersistence;

	@Reference
	protected PianoStatoRelPersistence pianoStatoRelPersistence;

	protected ProgettiFabbisogniLocalService progettiFabbisogniLocalService;

	@Reference
	protected ProgettiFabbisogniPersistence progettiFabbisogniPersistence;

	@Reference
	protected StatoAvanzamentoLavoriPersistence
		statoAvanzamentoLavoriPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

}