/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import servicebuilder.model.AttiDiAdesione;
import servicebuilder.model.AttiDiAdesioneModel;

/**
 * The base model implementation for the AttiDiAdesione service. Represents a row in the &quot;AQ_AttiDiAdesione&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>AttiDiAdesioneModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link AttiDiAdesioneImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see AttiDiAdesioneImpl
 * @generated
 */
public class AttiDiAdesioneModelImpl
	extends BaseModelImpl<AttiDiAdesione> implements AttiDiAdesioneModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a atti di adesione model instance should use the <code>AttiDiAdesione</code> interface instead.
	 */
	public static final String TABLE_NAME = "AQ_AttiDiAdesione";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id_AttiDiAdesione", Types.BIGINT},
		{"CodiceAttoDiAdesione", Types.VARCHAR}, {"FK_documenti", Types.BIGINT},
		{"FK_accordoQuadro", Types.BIGINT}, {"Anno", Types.INTEGER},
		{"Stato", Types.VARCHAR}, {"DataStato", Types.TIMESTAMP},
		{"Descrizione", Types.VARCHAR}, {"ImportoComplessivo", Types.DOUBLE},
		{"userIns", Types.VARCHAR}, {"userAgg", Types.VARCHAR},
		{"dataIns", Types.TIMESTAMP}, {"dataAgg", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id_AttiDiAdesione", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CodiceAttoDiAdesione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FK_documenti", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FK_accordoQuadro", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Anno", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("Stato", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DataStato", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Descrizione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("ImportoComplessivo", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("userIns", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userAgg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataIns", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataAgg", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AQ_AttiDiAdesione (Id_AttiDiAdesione LONG not null primary key,CodiceAttoDiAdesione VARCHAR(75) null,FK_documenti LONG,FK_accordoQuadro LONG,Anno INTEGER,Stato VARCHAR(75) null,DataStato DATE null,Descrizione VARCHAR(75) null,ImportoComplessivo DOUBLE,userIns VARCHAR(75) null,userAgg VARCHAR(75) null,dataIns DATE null,dataAgg DATE null)";

	public static final String TABLE_SQL_DROP = "drop table AQ_AttiDiAdesione";

	public static final String ORDER_BY_JPQL =
		" ORDER BY attiDiAdesione.Id_AttiDiAdesione ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AQ_AttiDiAdesione.Id_AttiDiAdesione ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FK_ACCORDOQUADRO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_ATTIDIADESIONE_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public AttiDiAdesioneModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id_AttiDiAdesione;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_AttiDiAdesione(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id_AttiDiAdesione;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return AttiDiAdesione.class;
	}

	@Override
	public String getModelClassName() {
		return AttiDiAdesione.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<AttiDiAdesione, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<AttiDiAdesione, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AttiDiAdesione, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((AttiDiAdesione)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<AttiDiAdesione, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<AttiDiAdesione, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(AttiDiAdesione)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<AttiDiAdesione, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<AttiDiAdesione, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<AttiDiAdesione, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<AttiDiAdesione, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<AttiDiAdesione, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<AttiDiAdesione, Object>>();
		Map<String, BiConsumer<AttiDiAdesione, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<AttiDiAdesione, ?>>();

		attributeGetterFunctions.put(
			"Id_AttiDiAdesione", AttiDiAdesione::getId_AttiDiAdesione);
		attributeSetterBiConsumers.put(
			"Id_AttiDiAdesione",
			(BiConsumer<AttiDiAdesione, Long>)
				AttiDiAdesione::setId_AttiDiAdesione);
		attributeGetterFunctions.put(
			"CodiceAttoDiAdesione", AttiDiAdesione::getCodiceAttoDiAdesione);
		attributeSetterBiConsumers.put(
			"CodiceAttoDiAdesione",
			(BiConsumer<AttiDiAdesione, String>)
				AttiDiAdesione::setCodiceAttoDiAdesione);
		attributeGetterFunctions.put(
			"FK_documenti", AttiDiAdesione::getFK_documenti);
		attributeSetterBiConsumers.put(
			"FK_documenti",
			(BiConsumer<AttiDiAdesione, Long>)AttiDiAdesione::setFK_documenti);
		attributeGetterFunctions.put(
			"FK_accordoQuadro", AttiDiAdesione::getFK_accordoQuadro);
		attributeSetterBiConsumers.put(
			"FK_accordoQuadro",
			(BiConsumer<AttiDiAdesione, Long>)
				AttiDiAdesione::setFK_accordoQuadro);
		attributeGetterFunctions.put("Anno", AttiDiAdesione::getAnno);
		attributeSetterBiConsumers.put(
			"Anno",
			(BiConsumer<AttiDiAdesione, Integer>)AttiDiAdesione::setAnno);
		attributeGetterFunctions.put("Stato", AttiDiAdesione::getStato);
		attributeSetterBiConsumers.put(
			"Stato",
			(BiConsumer<AttiDiAdesione, String>)AttiDiAdesione::setStato);
		attributeGetterFunctions.put("DataStato", AttiDiAdesione::getDataStato);
		attributeSetterBiConsumers.put(
			"DataStato",
			(BiConsumer<AttiDiAdesione, Date>)AttiDiAdesione::setDataStato);
		attributeGetterFunctions.put(
			"Descrizione", AttiDiAdesione::getDescrizione);
		attributeSetterBiConsumers.put(
			"Descrizione",
			(BiConsumer<AttiDiAdesione, String>)AttiDiAdesione::setDescrizione);
		attributeGetterFunctions.put(
			"ImportoComplessivo", AttiDiAdesione::getImportoComplessivo);
		attributeSetterBiConsumers.put(
			"ImportoComplessivo",
			(BiConsumer<AttiDiAdesione, Double>)
				AttiDiAdesione::setImportoComplessivo);
		attributeGetterFunctions.put("userIns", AttiDiAdesione::getUserIns);
		attributeSetterBiConsumers.put(
			"userIns",
			(BiConsumer<AttiDiAdesione, String>)AttiDiAdesione::setUserIns);
		attributeGetterFunctions.put("userAgg", AttiDiAdesione::getUserAgg);
		attributeSetterBiConsumers.put(
			"userAgg",
			(BiConsumer<AttiDiAdesione, String>)AttiDiAdesione::setUserAgg);
		attributeGetterFunctions.put("dataIns", AttiDiAdesione::getDataIns);
		attributeSetterBiConsumers.put(
			"dataIns",
			(BiConsumer<AttiDiAdesione, Date>)AttiDiAdesione::setDataIns);
		attributeGetterFunctions.put("dataAgg", AttiDiAdesione::getDataAgg);
		attributeSetterBiConsumers.put(
			"dataAgg",
			(BiConsumer<AttiDiAdesione, Date>)AttiDiAdesione::setDataAgg);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId_AttiDiAdesione() {
		return _Id_AttiDiAdesione;
	}

	@Override
	public void setId_AttiDiAdesione(long Id_AttiDiAdesione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id_AttiDiAdesione = Id_AttiDiAdesione;
	}

	@Override
	public String getCodiceAttoDiAdesione() {
		if (_CodiceAttoDiAdesione == null) {
			return "";
		}
		else {
			return _CodiceAttoDiAdesione;
		}
	}

	@Override
	public void setCodiceAttoDiAdesione(String CodiceAttoDiAdesione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CodiceAttoDiAdesione = CodiceAttoDiAdesione;
	}

	@Override
	public long getFK_documenti() {
		return _FK_documenti;
	}

	@Override
	public void setFK_documenti(long FK_documenti) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_documenti = FK_documenti;
	}

	@Override
	public long getFK_accordoQuadro() {
		return _FK_accordoQuadro;
	}

	@Override
	public void setFK_accordoQuadro(long FK_accordoQuadro) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_accordoQuadro = FK_accordoQuadro;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFK_accordoQuadro() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("FK_accordoQuadro"));
	}

	@Override
	public Integer getAnno() {
		return _Anno;
	}

	@Override
	public void setAnno(Integer Anno) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Anno = Anno;
	}

	@Override
	public String getStato() {
		if (_Stato == null) {
			return "";
		}
		else {
			return _Stato;
		}
	}

	@Override
	public void setStato(String Stato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Stato = Stato;
	}

	@Override
	public Date getDataStato() {
		return _DataStato;
	}

	@Override
	public void setDataStato(Date DataStato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataStato = DataStato;
	}

	@Override
	public String getDescrizione() {
		if (_Descrizione == null) {
			return "";
		}
		else {
			return _Descrizione;
		}
	}

	@Override
	public void setDescrizione(String Descrizione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Descrizione = Descrizione;
	}

	@Override
	public Double getImportoComplessivo() {
		return _ImportoComplessivo;
	}

	@Override
	public void setImportoComplessivo(Double ImportoComplessivo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImportoComplessivo = ImportoComplessivo;
	}

	@Override
	public String getUserIns() {
		if (_userIns == null) {
			return "";
		}
		else {
			return _userIns;
		}
	}

	@Override
	public void setUserIns(String userIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userIns = userIns;
	}

	@Override
	public String getUserAgg() {
		if (_userAgg == null) {
			return "";
		}
		else {
			return _userAgg;
		}
	}

	@Override
	public void setUserAgg(String userAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userAgg = userAgg;
	}

	@Override
	public Date getDataIns() {
		return _dataIns;
	}

	@Override
	public void setDataIns(Date dataIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataIns = dataIns;
	}

	@Override
	public Date getDataAgg() {
		return _dataAgg;
	}

	@Override
	public void setDataAgg(Date dataAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataAgg = dataAgg;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, AttiDiAdesione.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public AttiDiAdesione toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, AttiDiAdesione>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		AttiDiAdesioneImpl attiDiAdesioneImpl = new AttiDiAdesioneImpl();

		attiDiAdesioneImpl.setId_AttiDiAdesione(getId_AttiDiAdesione());
		attiDiAdesioneImpl.setCodiceAttoDiAdesione(getCodiceAttoDiAdesione());
		attiDiAdesioneImpl.setFK_documenti(getFK_documenti());
		attiDiAdesioneImpl.setFK_accordoQuadro(getFK_accordoQuadro());
		attiDiAdesioneImpl.setAnno(getAnno());
		attiDiAdesioneImpl.setStato(getStato());
		attiDiAdesioneImpl.setDataStato(getDataStato());
		attiDiAdesioneImpl.setDescrizione(getDescrizione());
		attiDiAdesioneImpl.setImportoComplessivo(getImportoComplessivo());
		attiDiAdesioneImpl.setUserIns(getUserIns());
		attiDiAdesioneImpl.setUserAgg(getUserAgg());
		attiDiAdesioneImpl.setDataIns(getDataIns());
		attiDiAdesioneImpl.setDataAgg(getDataAgg());

		attiDiAdesioneImpl.resetOriginalValues();

		return attiDiAdesioneImpl;
	}

	@Override
	public AttiDiAdesione cloneWithOriginalValues() {
		AttiDiAdesioneImpl attiDiAdesioneImpl = new AttiDiAdesioneImpl();

		attiDiAdesioneImpl.setId_AttiDiAdesione(
			this.<Long>getColumnOriginalValue("Id_AttiDiAdesione"));
		attiDiAdesioneImpl.setCodiceAttoDiAdesione(
			this.<String>getColumnOriginalValue("CodiceAttoDiAdesione"));
		attiDiAdesioneImpl.setFK_documenti(
			this.<Long>getColumnOriginalValue("FK_documenti"));
		attiDiAdesioneImpl.setFK_accordoQuadro(
			this.<Long>getColumnOriginalValue("FK_accordoQuadro"));
		attiDiAdesioneImpl.setAnno(
			this.<Integer>getColumnOriginalValue("Anno"));
		attiDiAdesioneImpl.setStato(
			this.<String>getColumnOriginalValue("Stato"));
		attiDiAdesioneImpl.setDataStato(
			this.<Date>getColumnOriginalValue("DataStato"));
		attiDiAdesioneImpl.setDescrizione(
			this.<String>getColumnOriginalValue("Descrizione"));
		attiDiAdesioneImpl.setImportoComplessivo(
			this.<Double>getColumnOriginalValue("ImportoComplessivo"));
		attiDiAdesioneImpl.setUserIns(
			this.<String>getColumnOriginalValue("userIns"));
		attiDiAdesioneImpl.setUserAgg(
			this.<String>getColumnOriginalValue("userAgg"));
		attiDiAdesioneImpl.setDataIns(
			this.<Date>getColumnOriginalValue("dataIns"));
		attiDiAdesioneImpl.setDataAgg(
			this.<Date>getColumnOriginalValue("dataAgg"));

		return attiDiAdesioneImpl;
	}

	@Override
	public int compareTo(AttiDiAdesione attiDiAdesione) {
		long primaryKey = attiDiAdesione.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof AttiDiAdesione)) {
			return false;
		}

		AttiDiAdesione attiDiAdesione = (AttiDiAdesione)object;

		long primaryKey = attiDiAdesione.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<AttiDiAdesione> toCacheModel() {
		AttiDiAdesioneCacheModel attiDiAdesioneCacheModel =
			new AttiDiAdesioneCacheModel();

		attiDiAdesioneCacheModel.Id_AttiDiAdesione = getId_AttiDiAdesione();

		attiDiAdesioneCacheModel.CodiceAttoDiAdesione =
			getCodiceAttoDiAdesione();

		String CodiceAttoDiAdesione =
			attiDiAdesioneCacheModel.CodiceAttoDiAdesione;

		if ((CodiceAttoDiAdesione != null) &&
			(CodiceAttoDiAdesione.length() == 0)) {

			attiDiAdesioneCacheModel.CodiceAttoDiAdesione = null;
		}

		attiDiAdesioneCacheModel.FK_documenti = getFK_documenti();

		attiDiAdesioneCacheModel.FK_accordoQuadro = getFK_accordoQuadro();

		Integer Anno = getAnno();

		if (Anno != null) {
			attiDiAdesioneCacheModel.Anno = Anno;
		}

		attiDiAdesioneCacheModel.Stato = getStato();

		String Stato = attiDiAdesioneCacheModel.Stato;

		if ((Stato != null) && (Stato.length() == 0)) {
			attiDiAdesioneCacheModel.Stato = null;
		}

		Date DataStato = getDataStato();

		if (DataStato != null) {
			attiDiAdesioneCacheModel.DataStato = DataStato.getTime();
		}
		else {
			attiDiAdesioneCacheModel.DataStato = Long.MIN_VALUE;
		}

		attiDiAdesioneCacheModel.Descrizione = getDescrizione();

		String Descrizione = attiDiAdesioneCacheModel.Descrizione;

		if ((Descrizione != null) && (Descrizione.length() == 0)) {
			attiDiAdesioneCacheModel.Descrizione = null;
		}

		Double ImportoComplessivo = getImportoComplessivo();

		if (ImportoComplessivo != null) {
			attiDiAdesioneCacheModel.ImportoComplessivo = ImportoComplessivo;
		}

		attiDiAdesioneCacheModel.userIns = getUserIns();

		String userIns = attiDiAdesioneCacheModel.userIns;

		if ((userIns != null) && (userIns.length() == 0)) {
			attiDiAdesioneCacheModel.userIns = null;
		}

		attiDiAdesioneCacheModel.userAgg = getUserAgg();

		String userAgg = attiDiAdesioneCacheModel.userAgg;

		if ((userAgg != null) && (userAgg.length() == 0)) {
			attiDiAdesioneCacheModel.userAgg = null;
		}

		Date dataIns = getDataIns();

		if (dataIns != null) {
			attiDiAdesioneCacheModel.dataIns = dataIns.getTime();
		}
		else {
			attiDiAdesioneCacheModel.dataIns = Long.MIN_VALUE;
		}

		Date dataAgg = getDataAgg();

		if (dataAgg != null) {
			attiDiAdesioneCacheModel.dataAgg = dataAgg.getTime();
		}
		else {
			attiDiAdesioneCacheModel.dataAgg = Long.MIN_VALUE;
		}

		return attiDiAdesioneCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<AttiDiAdesione, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<AttiDiAdesione, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AttiDiAdesione, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((AttiDiAdesione)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<AttiDiAdesione, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<AttiDiAdesione, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<AttiDiAdesione, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((AttiDiAdesione)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, AttiDiAdesione>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					AttiDiAdesione.class, ModelWrapper.class);

	}

	private long _Id_AttiDiAdesione;
	private String _CodiceAttoDiAdesione;
	private long _FK_documenti;
	private long _FK_accordoQuadro;
	private Integer _Anno;
	private String _Stato;
	private Date _DataStato;
	private String _Descrizione;
	private Double _ImportoComplessivo;
	private String _userIns;
	private String _userAgg;
	private Date _dataIns;
	private Date _dataAgg;

	public <T> T getColumnValue(String columnName) {
		Function<AttiDiAdesione, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((AttiDiAdesione)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id_AttiDiAdesione", _Id_AttiDiAdesione);
		_columnOriginalValues.put(
			"CodiceAttoDiAdesione", _CodiceAttoDiAdesione);
		_columnOriginalValues.put("FK_documenti", _FK_documenti);
		_columnOriginalValues.put("FK_accordoQuadro", _FK_accordoQuadro);
		_columnOriginalValues.put("Anno", _Anno);
		_columnOriginalValues.put("Stato", _Stato);
		_columnOriginalValues.put("DataStato", _DataStato);
		_columnOriginalValues.put("Descrizione", _Descrizione);
		_columnOriginalValues.put("ImportoComplessivo", _ImportoComplessivo);
		_columnOriginalValues.put("userIns", _userIns);
		_columnOriginalValues.put("userAgg", _userAgg);
		_columnOriginalValues.put("dataIns", _dataIns);
		_columnOriginalValues.put("dataAgg", _dataAgg);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id_AttiDiAdesione", 1L);

		columnBitmasks.put("CodiceAttoDiAdesione", 2L);

		columnBitmasks.put("FK_documenti", 4L);

		columnBitmasks.put("FK_accordoQuadro", 8L);

		columnBitmasks.put("Anno", 16L);

		columnBitmasks.put("Stato", 32L);

		columnBitmasks.put("DataStato", 64L);

		columnBitmasks.put("Descrizione", 128L);

		columnBitmasks.put("ImportoComplessivo", 256L);

		columnBitmasks.put("userIns", 512L);

		columnBitmasks.put("userAgg", 1024L);

		columnBitmasks.put("dataIns", 2048L);

		columnBitmasks.put("dataAgg", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private AttiDiAdesione _escapedModel;

}