/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model.impl;

import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import servicebuilder.model.ContrattiEsecutivi;
import servicebuilder.model.ContrattiEsecutiviModel;

import servicebuilder.service.persistence.ContrattiEsecutiviPK;

/**
 * The base model implementation for the ContrattiEsecutivi service. Represents a row in the &quot;AQ_ContrattiEsecutivi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ContrattiEsecutiviModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ContrattiEsecutiviImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ContrattiEsecutiviImpl
 * @generated
 */
public class ContrattiEsecutiviModelImpl
	extends BaseModelImpl<ContrattiEsecutivi>
	implements ContrattiEsecutiviModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a contratti esecutivi model instance should use the <code>ContrattiEsecutivi</code> interface instead.
	 */
	public static final String TABLE_NAME = "AQ_ContrattiEsecutivi";

	public static final Object[][] TABLE_COLUMNS = {
		{"CodiceContratto", Types.VARCHAR},
		{"Id_ContrattiEsecutivi", Types.BIGINT}, {"FK_documenti", Types.BIGINT},
		{"FK_progettiFabbisogni", Types.BIGINT}, {"Descrizione", Types.VARCHAR},
		{"Stato", Types.VARCHAR}, {"DataStato", Types.TIMESTAMP},
		{"DataInizioContratto", Types.TIMESTAMP},
		{"DataFineContratto", Types.TIMESTAMP},
		{"ImportoComplessivo", Types.DOUBLE}, {"userIns", Types.VARCHAR},
		{"userAgg", Types.VARCHAR}, {"dataIns", Types.TIMESTAMP},
		{"dataAgg", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("CodiceContratto", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Id_ContrattiEsecutivi", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FK_documenti", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FK_progettiFabbisogni", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Descrizione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Stato", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DataStato", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("DataInizioContratto", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("DataFineContratto", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ImportoComplessivo", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("userIns", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userAgg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataIns", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataAgg", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AQ_ContrattiEsecutivi (CodiceContratto VARCHAR(75) not null,Id_ContrattiEsecutivi LONG not null,FK_documenti LONG,FK_progettiFabbisogni LONG,Descrizione VARCHAR(75) null,Stato VARCHAR(75) null,DataStato DATE null,DataInizioContratto DATE null,DataFineContratto DATE null,ImportoComplessivo DOUBLE,userIns VARCHAR(75) null,userAgg VARCHAR(75) null,dataIns DATE null,dataAgg DATE null,primary key (CodiceContratto, Id_ContrattiEsecutivi))";

	public static final String TABLE_SQL_DROP =
		"drop table AQ_ContrattiEsecutivi";

	public static final String ORDER_BY_JPQL =
		" ORDER BY contrattiEsecutivi.id.CodiceContratto ASC, contrattiEsecutivi.id.Id_ContrattiEsecutivi ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AQ_ContrattiEsecutivi.CodiceContratto ASC, AQ_ContrattiEsecutivi.Id_ContrattiEsecutivi ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long CODICECONTRATTO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_CONTRATTIESECUTIVI_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ContrattiEsecutiviModelImpl() {
	}

	@Override
	public ContrattiEsecutiviPK getPrimaryKey() {
		return new ContrattiEsecutiviPK(
			_CodiceContratto, _Id_ContrattiEsecutivi);
	}

	@Override
	public void setPrimaryKey(ContrattiEsecutiviPK primaryKey) {
		setCodiceContratto(primaryKey.CodiceContratto);
		setId_ContrattiEsecutivi(primaryKey.Id_ContrattiEsecutivi);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return new ContrattiEsecutiviPK(
			_CodiceContratto, _Id_ContrattiEsecutivi);
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey((ContrattiEsecutiviPK)primaryKeyObj);
	}

	@Override
	public Class<?> getModelClass() {
		return ContrattiEsecutivi.class;
	}

	@Override
	public String getModelClassName() {
		return ContrattiEsecutivi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ContrattiEsecutivi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ContrattiEsecutivi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContrattiEsecutivi, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ContrattiEsecutivi)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ContrattiEsecutivi, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ContrattiEsecutivi, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ContrattiEsecutivi)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ContrattiEsecutivi, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ContrattiEsecutivi, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ContrattiEsecutivi, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ContrattiEsecutivi, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ContrattiEsecutivi, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ContrattiEsecutivi, Object>>();
		Map<String, BiConsumer<ContrattiEsecutivi, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ContrattiEsecutivi, ?>>();

		attributeGetterFunctions.put(
			"CodiceContratto", ContrattiEsecutivi::getCodiceContratto);
		attributeSetterBiConsumers.put(
			"CodiceContratto",
			(BiConsumer<ContrattiEsecutivi, String>)
				ContrattiEsecutivi::setCodiceContratto);
		attributeGetterFunctions.put(
			"Id_ContrattiEsecutivi",
			ContrattiEsecutivi::getId_ContrattiEsecutivi);
		attributeSetterBiConsumers.put(
			"Id_ContrattiEsecutivi",
			(BiConsumer<ContrattiEsecutivi, Long>)
				ContrattiEsecutivi::setId_ContrattiEsecutivi);
		attributeGetterFunctions.put(
			"FK_documenti", ContrattiEsecutivi::getFK_documenti);
		attributeSetterBiConsumers.put(
			"FK_documenti",
			(BiConsumer<ContrattiEsecutivi, Long>)
				ContrattiEsecutivi::setFK_documenti);
		attributeGetterFunctions.put(
			"FK_progettiFabbisogni",
			ContrattiEsecutivi::getFK_progettiFabbisogni);
		attributeSetterBiConsumers.put(
			"FK_progettiFabbisogni",
			(BiConsumer<ContrattiEsecutivi, Long>)
				ContrattiEsecutivi::setFK_progettiFabbisogni);
		attributeGetterFunctions.put(
			"Descrizione", ContrattiEsecutivi::getDescrizione);
		attributeSetterBiConsumers.put(
			"Descrizione",
			(BiConsumer<ContrattiEsecutivi, String>)
				ContrattiEsecutivi::setDescrizione);
		attributeGetterFunctions.put("Stato", ContrattiEsecutivi::getStato);
		attributeSetterBiConsumers.put(
			"Stato",
			(BiConsumer<ContrattiEsecutivi, String>)
				ContrattiEsecutivi::setStato);
		attributeGetterFunctions.put(
			"DataStato", ContrattiEsecutivi::getDataStato);
		attributeSetterBiConsumers.put(
			"DataStato",
			(BiConsumer<ContrattiEsecutivi, Date>)
				ContrattiEsecutivi::setDataStato);
		attributeGetterFunctions.put(
			"DataInizioContratto", ContrattiEsecutivi::getDataInizioContratto);
		attributeSetterBiConsumers.put(
			"DataInizioContratto",
			(BiConsumer<ContrattiEsecutivi, Date>)
				ContrattiEsecutivi::setDataInizioContratto);
		attributeGetterFunctions.put(
			"DataFineContratto", ContrattiEsecutivi::getDataFineContratto);
		attributeSetterBiConsumers.put(
			"DataFineContratto",
			(BiConsumer<ContrattiEsecutivi, Date>)
				ContrattiEsecutivi::setDataFineContratto);
		attributeGetterFunctions.put(
			"ImportoComplessivo", ContrattiEsecutivi::getImportoComplessivo);
		attributeSetterBiConsumers.put(
			"ImportoComplessivo",
			(BiConsumer<ContrattiEsecutivi, Double>)
				ContrattiEsecutivi::setImportoComplessivo);
		attributeGetterFunctions.put("userIns", ContrattiEsecutivi::getUserIns);
		attributeSetterBiConsumers.put(
			"userIns",
			(BiConsumer<ContrattiEsecutivi, String>)
				ContrattiEsecutivi::setUserIns);
		attributeGetterFunctions.put("userAgg", ContrattiEsecutivi::getUserAgg);
		attributeSetterBiConsumers.put(
			"userAgg",
			(BiConsumer<ContrattiEsecutivi, String>)
				ContrattiEsecutivi::setUserAgg);
		attributeGetterFunctions.put("dataIns", ContrattiEsecutivi::getDataIns);
		attributeSetterBiConsumers.put(
			"dataIns",
			(BiConsumer<ContrattiEsecutivi, Date>)
				ContrattiEsecutivi::setDataIns);
		attributeGetterFunctions.put("dataAgg", ContrattiEsecutivi::getDataAgg);
		attributeSetterBiConsumers.put(
			"dataAgg",
			(BiConsumer<ContrattiEsecutivi, Date>)
				ContrattiEsecutivi::setDataAgg);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public String getCodiceContratto() {
		if (_CodiceContratto == null) {
			return "";
		}
		else {
			return _CodiceContratto;
		}
	}

	@Override
	public void setCodiceContratto(String CodiceContratto) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CodiceContratto = CodiceContratto;
	}

	@Override
	public long getId_ContrattiEsecutivi() {
		return _Id_ContrattiEsecutivi;
	}

	@Override
	public void setId_ContrattiEsecutivi(long Id_ContrattiEsecutivi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id_ContrattiEsecutivi = Id_ContrattiEsecutivi;
	}

	@Override
	public long getFK_documenti() {
		return _FK_documenti;
	}

	@Override
	public void setFK_documenti(long FK_documenti) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_documenti = FK_documenti;
	}

	@Override
	public long getFK_progettiFabbisogni() {
		return _FK_progettiFabbisogni;
	}

	@Override
	public void setFK_progettiFabbisogni(long FK_progettiFabbisogni) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_progettiFabbisogni = FK_progettiFabbisogni;
	}

	@Override
	public String getDescrizione() {
		if (_Descrizione == null) {
			return "";
		}
		else {
			return _Descrizione;
		}
	}

	@Override
	public void setDescrizione(String Descrizione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Descrizione = Descrizione;
	}

	@Override
	public String getStato() {
		if (_Stato == null) {
			return "";
		}
		else {
			return _Stato;
		}
	}

	@Override
	public void setStato(String Stato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Stato = Stato;
	}

	@Override
	public Date getDataStato() {
		return _DataStato;
	}

	@Override
	public void setDataStato(Date DataStato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataStato = DataStato;
	}

	@Override
	public Date getDataInizioContratto() {
		return _DataInizioContratto;
	}

	@Override
	public void setDataInizioContratto(Date DataInizioContratto) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataInizioContratto = DataInizioContratto;
	}

	@Override
	public Date getDataFineContratto() {
		return _DataFineContratto;
	}

	@Override
	public void setDataFineContratto(Date DataFineContratto) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataFineContratto = DataFineContratto;
	}

	@Override
	public Double getImportoComplessivo() {
		return _ImportoComplessivo;
	}

	@Override
	public void setImportoComplessivo(Double ImportoComplessivo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImportoComplessivo = ImportoComplessivo;
	}

	@Override
	public String getUserIns() {
		if (_userIns == null) {
			return "";
		}
		else {
			return _userIns;
		}
	}

	@Override
	public void setUserIns(String userIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userIns = userIns;
	}

	@Override
	public String getUserAgg() {
		if (_userAgg == null) {
			return "";
		}
		else {
			return _userAgg;
		}
	}

	@Override
	public void setUserAgg(String userAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userAgg = userAgg;
	}

	@Override
	public Date getDataIns() {
		return _dataIns;
	}

	@Override
	public void setDataIns(Date dataIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataIns = dataIns;
	}

	@Override
	public Date getDataAgg() {
		return _dataAgg;
	}

	@Override
	public void setDataAgg(Date dataAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataAgg = dataAgg;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ContrattiEsecutivi toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ContrattiEsecutivi>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ContrattiEsecutiviImpl contrattiEsecutiviImpl =
			new ContrattiEsecutiviImpl();

		contrattiEsecutiviImpl.setCodiceContratto(getCodiceContratto());
		contrattiEsecutiviImpl.setId_ContrattiEsecutivi(
			getId_ContrattiEsecutivi());
		contrattiEsecutiviImpl.setFK_documenti(getFK_documenti());
		contrattiEsecutiviImpl.setFK_progettiFabbisogni(
			getFK_progettiFabbisogni());
		contrattiEsecutiviImpl.setDescrizione(getDescrizione());
		contrattiEsecutiviImpl.setStato(getStato());
		contrattiEsecutiviImpl.setDataStato(getDataStato());
		contrattiEsecutiviImpl.setDataInizioContratto(getDataInizioContratto());
		contrattiEsecutiviImpl.setDataFineContratto(getDataFineContratto());
		contrattiEsecutiviImpl.setImportoComplessivo(getImportoComplessivo());
		contrattiEsecutiviImpl.setUserIns(getUserIns());
		contrattiEsecutiviImpl.setUserAgg(getUserAgg());
		contrattiEsecutiviImpl.setDataIns(getDataIns());
		contrattiEsecutiviImpl.setDataAgg(getDataAgg());

		contrattiEsecutiviImpl.resetOriginalValues();

		return contrattiEsecutiviImpl;
	}

	@Override
	public ContrattiEsecutivi cloneWithOriginalValues() {
		ContrattiEsecutiviImpl contrattiEsecutiviImpl =
			new ContrattiEsecutiviImpl();

		contrattiEsecutiviImpl.setCodiceContratto(
			this.<String>getColumnOriginalValue("CodiceContratto"));
		contrattiEsecutiviImpl.setId_ContrattiEsecutivi(
			this.<Long>getColumnOriginalValue("Id_ContrattiEsecutivi"));
		contrattiEsecutiviImpl.setFK_documenti(
			this.<Long>getColumnOriginalValue("FK_documenti"));
		contrattiEsecutiviImpl.setFK_progettiFabbisogni(
			this.<Long>getColumnOriginalValue("FK_progettiFabbisogni"));
		contrattiEsecutiviImpl.setDescrizione(
			this.<String>getColumnOriginalValue("Descrizione"));
		contrattiEsecutiviImpl.setStato(
			this.<String>getColumnOriginalValue("Stato"));
		contrattiEsecutiviImpl.setDataStato(
			this.<Date>getColumnOriginalValue("DataStato"));
		contrattiEsecutiviImpl.setDataInizioContratto(
			this.<Date>getColumnOriginalValue("DataInizioContratto"));
		contrattiEsecutiviImpl.setDataFineContratto(
			this.<Date>getColumnOriginalValue("DataFineContratto"));
		contrattiEsecutiviImpl.setImportoComplessivo(
			this.<Double>getColumnOriginalValue("ImportoComplessivo"));
		contrattiEsecutiviImpl.setUserIns(
			this.<String>getColumnOriginalValue("userIns"));
		contrattiEsecutiviImpl.setUserAgg(
			this.<String>getColumnOriginalValue("userAgg"));
		contrattiEsecutiviImpl.setDataIns(
			this.<Date>getColumnOriginalValue("dataIns"));
		contrattiEsecutiviImpl.setDataAgg(
			this.<Date>getColumnOriginalValue("dataAgg"));

		return contrattiEsecutiviImpl;
	}

	@Override
	public int compareTo(ContrattiEsecutivi contrattiEsecutivi) {
		ContrattiEsecutiviPK primaryKey = contrattiEsecutivi.getPrimaryKey();

		return getPrimaryKey().compareTo(primaryKey);
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ContrattiEsecutivi)) {
			return false;
		}

		ContrattiEsecutivi contrattiEsecutivi = (ContrattiEsecutivi)object;

		ContrattiEsecutiviPK primaryKey = contrattiEsecutivi.getPrimaryKey();

		if (getPrimaryKey().equals(primaryKey)) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ContrattiEsecutivi> toCacheModel() {
		ContrattiEsecutiviCacheModel contrattiEsecutiviCacheModel =
			new ContrattiEsecutiviCacheModel();

		contrattiEsecutiviCacheModel.contrattiEsecutiviPK = getPrimaryKey();

		contrattiEsecutiviCacheModel.CodiceContratto = getCodiceContratto();

		String CodiceContratto = contrattiEsecutiviCacheModel.CodiceContratto;

		if ((CodiceContratto != null) && (CodiceContratto.length() == 0)) {
			contrattiEsecutiviCacheModel.CodiceContratto = null;
		}

		contrattiEsecutiviCacheModel.Id_ContrattiEsecutivi =
			getId_ContrattiEsecutivi();

		contrattiEsecutiviCacheModel.FK_documenti = getFK_documenti();

		contrattiEsecutiviCacheModel.FK_progettiFabbisogni =
			getFK_progettiFabbisogni();

		contrattiEsecutiviCacheModel.Descrizione = getDescrizione();

		String Descrizione = contrattiEsecutiviCacheModel.Descrizione;

		if ((Descrizione != null) && (Descrizione.length() == 0)) {
			contrattiEsecutiviCacheModel.Descrizione = null;
		}

		contrattiEsecutiviCacheModel.Stato = getStato();

		String Stato = contrattiEsecutiviCacheModel.Stato;

		if ((Stato != null) && (Stato.length() == 0)) {
			contrattiEsecutiviCacheModel.Stato = null;
		}

		Date DataStato = getDataStato();

		if (DataStato != null) {
			contrattiEsecutiviCacheModel.DataStato = DataStato.getTime();
		}
		else {
			contrattiEsecutiviCacheModel.DataStato = Long.MIN_VALUE;
		}

		Date DataInizioContratto = getDataInizioContratto();

		if (DataInizioContratto != null) {
			contrattiEsecutiviCacheModel.DataInizioContratto =
				DataInizioContratto.getTime();
		}
		else {
			contrattiEsecutiviCacheModel.DataInizioContratto = Long.MIN_VALUE;
		}

		Date DataFineContratto = getDataFineContratto();

		if (DataFineContratto != null) {
			contrattiEsecutiviCacheModel.DataFineContratto =
				DataFineContratto.getTime();
		}
		else {
			contrattiEsecutiviCacheModel.DataFineContratto = Long.MIN_VALUE;
		}

		Double ImportoComplessivo = getImportoComplessivo();

		if (ImportoComplessivo != null) {
			contrattiEsecutiviCacheModel.ImportoComplessivo =
				ImportoComplessivo;
		}

		contrattiEsecutiviCacheModel.userIns = getUserIns();

		String userIns = contrattiEsecutiviCacheModel.userIns;

		if ((userIns != null) && (userIns.length() == 0)) {
			contrattiEsecutiviCacheModel.userIns = null;
		}

		contrattiEsecutiviCacheModel.userAgg = getUserAgg();

		String userAgg = contrattiEsecutiviCacheModel.userAgg;

		if ((userAgg != null) && (userAgg.length() == 0)) {
			contrattiEsecutiviCacheModel.userAgg = null;
		}

		Date dataIns = getDataIns();

		if (dataIns != null) {
			contrattiEsecutiviCacheModel.dataIns = dataIns.getTime();
		}
		else {
			contrattiEsecutiviCacheModel.dataIns = Long.MIN_VALUE;
		}

		Date dataAgg = getDataAgg();

		if (dataAgg != null) {
			contrattiEsecutiviCacheModel.dataAgg = dataAgg.getTime();
		}
		else {
			contrattiEsecutiviCacheModel.dataAgg = Long.MIN_VALUE;
		}

		return contrattiEsecutiviCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ContrattiEsecutivi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ContrattiEsecutivi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContrattiEsecutivi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ContrattiEsecutivi)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ContrattiEsecutivi, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ContrattiEsecutivi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ContrattiEsecutivi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ContrattiEsecutivi)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ContrattiEsecutivi>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ContrattiEsecutivi.class, ModelWrapper.class);

	}

	private String _CodiceContratto;
	private long _Id_ContrattiEsecutivi;
	private long _FK_documenti;
	private long _FK_progettiFabbisogni;
	private String _Descrizione;
	private String _Stato;
	private Date _DataStato;
	private Date _DataInizioContratto;
	private Date _DataFineContratto;
	private Double _ImportoComplessivo;
	private String _userIns;
	private String _userAgg;
	private Date _dataIns;
	private Date _dataAgg;

	public <T> T getColumnValue(String columnName) {
		Function<ContrattiEsecutivi, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ContrattiEsecutivi)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("CodiceContratto", _CodiceContratto);
		_columnOriginalValues.put(
			"Id_ContrattiEsecutivi", _Id_ContrattiEsecutivi);
		_columnOriginalValues.put("FK_documenti", _FK_documenti);
		_columnOriginalValues.put(
			"FK_progettiFabbisogni", _FK_progettiFabbisogni);
		_columnOriginalValues.put("Descrizione", _Descrizione);
		_columnOriginalValues.put("Stato", _Stato);
		_columnOriginalValues.put("DataStato", _DataStato);
		_columnOriginalValues.put("DataInizioContratto", _DataInizioContratto);
		_columnOriginalValues.put("DataFineContratto", _DataFineContratto);
		_columnOriginalValues.put("ImportoComplessivo", _ImportoComplessivo);
		_columnOriginalValues.put("userIns", _userIns);
		_columnOriginalValues.put("userAgg", _userAgg);
		_columnOriginalValues.put("dataIns", _dataIns);
		_columnOriginalValues.put("dataAgg", _dataAgg);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("CodiceContratto", 1L);

		columnBitmasks.put("Id_ContrattiEsecutivi", 2L);

		columnBitmasks.put("FK_documenti", 4L);

		columnBitmasks.put("FK_progettiFabbisogni", 8L);

		columnBitmasks.put("Descrizione", 16L);

		columnBitmasks.put("Stato", 32L);

		columnBitmasks.put("DataStato", 64L);

		columnBitmasks.put("DataInizioContratto", 128L);

		columnBitmasks.put("DataFineContratto", 256L);

		columnBitmasks.put("ImportoComplessivo", 512L);

		columnBitmasks.put("userIns", 1024L);

		columnBitmasks.put("userAgg", 2048L);

		columnBitmasks.put("dataIns", 4096L);

		columnBitmasks.put("dataAgg", 8192L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ContrattiEsecutivi _escapedModel;

}