/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import servicebuilder.model.PianiFabbisogni;
import servicebuilder.model.PianiFabbisogniModel;

/**
 * The base model implementation for the PianiFabbisogni service. Represents a row in the &quot;AQ_PianiFabbisogni&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PianiFabbisogniModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PianiFabbisogniImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PianiFabbisogniImpl
 * @generated
 */
public class PianiFabbisogniModelImpl
	extends BaseModelImpl<PianiFabbisogni> implements PianiFabbisogniModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a piani fabbisogni model instance should use the <code>PianiFabbisogni</code> interface instead.
	 */
	public static final String TABLE_NAME = "AQ_PianiFabbisogni";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id_PianiFabbisogni", Types.BIGINT},
		{"CodicePianoFabbisogno", Types.VARCHAR},
		{"FK_documenti", Types.BIGINT}, {"FK_attiDiAdesione", Types.BIGINT},
		{"Descrizione", Types.VARCHAR}, {"Stato", Types.VARCHAR},
		{"DataStato", Types.TIMESTAMP},
		{"DataInizioFabbisogni", Types.TIMESTAMP},
		{"DataFineFabbisogni", Types.TIMESTAMP}, {"userIns", Types.VARCHAR},
		{"userAgg", Types.VARCHAR}, {"dataIns", Types.TIMESTAMP},
		{"dataAgg", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id_PianiFabbisogni", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CodicePianoFabbisogno", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FK_documenti", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FK_attiDiAdesione", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Descrizione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("Stato", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DataStato", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("DataInizioFabbisogni", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("DataFineFabbisogni", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userIns", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userAgg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataIns", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataAgg", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AQ_PianiFabbisogni (Id_PianiFabbisogni LONG not null primary key,CodicePianoFabbisogno VARCHAR(75) null,FK_documenti LONG,FK_attiDiAdesione LONG,Descrizione VARCHAR(75) null,Stato VARCHAR(75) null,DataStato DATE null,DataInizioFabbisogni DATE null,DataFineFabbisogni DATE null,userIns VARCHAR(75) null,userAgg VARCHAR(75) null,dataIns DATE null,dataAgg DATE null)";

	public static final String TABLE_SQL_DROP = "drop table AQ_PianiFabbisogni";

	public static final String ORDER_BY_JPQL =
		" ORDER BY pianiFabbisogni.Id_PianiFabbisogni ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AQ_PianiFabbisogni.Id_PianiFabbisogni ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FK_ATTIDIADESIONE_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_PIANIFABBISOGNI_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PianiFabbisogniModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id_PianiFabbisogni;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_PianiFabbisogni(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id_PianiFabbisogni;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PianiFabbisogni.class;
	}

	@Override
	public String getModelClassName() {
		return PianiFabbisogni.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PianiFabbisogni, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PianiFabbisogni, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PianiFabbisogni, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PianiFabbisogni)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PianiFabbisogni, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PianiFabbisogni, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PianiFabbisogni)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PianiFabbisogni, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PianiFabbisogni, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<PianiFabbisogni, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PianiFabbisogni, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PianiFabbisogni, Object>>
			attributeGetterFunctions =
				new LinkedHashMap<String, Function<PianiFabbisogni, Object>>();
		Map<String, BiConsumer<PianiFabbisogni, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PianiFabbisogni, ?>>();

		attributeGetterFunctions.put(
			"Id_PianiFabbisogni", PianiFabbisogni::getId_PianiFabbisogni);
		attributeSetterBiConsumers.put(
			"Id_PianiFabbisogni",
			(BiConsumer<PianiFabbisogni, Long>)
				PianiFabbisogni::setId_PianiFabbisogni);
		attributeGetterFunctions.put(
			"CodicePianoFabbisogno", PianiFabbisogni::getCodicePianoFabbisogno);
		attributeSetterBiConsumers.put(
			"CodicePianoFabbisogno",
			(BiConsumer<PianiFabbisogni, String>)
				PianiFabbisogni::setCodicePianoFabbisogno);
		attributeGetterFunctions.put(
			"FK_documenti", PianiFabbisogni::getFK_documenti);
		attributeSetterBiConsumers.put(
			"FK_documenti",
			(BiConsumer<PianiFabbisogni, Long>)
				PianiFabbisogni::setFK_documenti);
		attributeGetterFunctions.put(
			"FK_attiDiAdesione", PianiFabbisogni::getFK_attiDiAdesione);
		attributeSetterBiConsumers.put(
			"FK_attiDiAdesione",
			(BiConsumer<PianiFabbisogni, Long>)
				PianiFabbisogni::setFK_attiDiAdesione);
		attributeGetterFunctions.put(
			"Descrizione", PianiFabbisogni::getDescrizione);
		attributeSetterBiConsumers.put(
			"Descrizione",
			(BiConsumer<PianiFabbisogni, String>)
				PianiFabbisogni::setDescrizione);
		attributeGetterFunctions.put("Stato", PianiFabbisogni::getStato);
		attributeSetterBiConsumers.put(
			"Stato",
			(BiConsumer<PianiFabbisogni, String>)PianiFabbisogni::setStato);
		attributeGetterFunctions.put(
			"DataStato", PianiFabbisogni::getDataStato);
		attributeSetterBiConsumers.put(
			"DataStato",
			(BiConsumer<PianiFabbisogni, Date>)PianiFabbisogni::setDataStato);
		attributeGetterFunctions.put(
			"DataInizioFabbisogni", PianiFabbisogni::getDataInizioFabbisogni);
		attributeSetterBiConsumers.put(
			"DataInizioFabbisogni",
			(BiConsumer<PianiFabbisogni, Date>)
				PianiFabbisogni::setDataInizioFabbisogni);
		attributeGetterFunctions.put(
			"DataFineFabbisogni", PianiFabbisogni::getDataFineFabbisogni);
		attributeSetterBiConsumers.put(
			"DataFineFabbisogni",
			(BiConsumer<PianiFabbisogni, Date>)
				PianiFabbisogni::setDataFineFabbisogni);
		attributeGetterFunctions.put("userIns", PianiFabbisogni::getUserIns);
		attributeSetterBiConsumers.put(
			"userIns",
			(BiConsumer<PianiFabbisogni, String>)PianiFabbisogni::setUserIns);
		attributeGetterFunctions.put("userAgg", PianiFabbisogni::getUserAgg);
		attributeSetterBiConsumers.put(
			"userAgg",
			(BiConsumer<PianiFabbisogni, String>)PianiFabbisogni::setUserAgg);
		attributeGetterFunctions.put("dataIns", PianiFabbisogni::getDataIns);
		attributeSetterBiConsumers.put(
			"dataIns",
			(BiConsumer<PianiFabbisogni, Date>)PianiFabbisogni::setDataIns);
		attributeGetterFunctions.put("dataAgg", PianiFabbisogni::getDataAgg);
		attributeSetterBiConsumers.put(
			"dataAgg",
			(BiConsumer<PianiFabbisogni, Date>)PianiFabbisogni::setDataAgg);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId_PianiFabbisogni() {
		return _Id_PianiFabbisogni;
	}

	@Override
	public void setId_PianiFabbisogni(long Id_PianiFabbisogni) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id_PianiFabbisogni = Id_PianiFabbisogni;
	}

	@Override
	public String getCodicePianoFabbisogno() {
		if (_CodicePianoFabbisogno == null) {
			return "";
		}
		else {
			return _CodicePianoFabbisogno;
		}
	}

	@Override
	public void setCodicePianoFabbisogno(String CodicePianoFabbisogno) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CodicePianoFabbisogno = CodicePianoFabbisogno;
	}

	@Override
	public long getFK_documenti() {
		return _FK_documenti;
	}

	@Override
	public void setFK_documenti(long FK_documenti) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_documenti = FK_documenti;
	}

	@Override
	public long getFK_attiDiAdesione() {
		return _FK_attiDiAdesione;
	}

	@Override
	public void setFK_attiDiAdesione(long FK_attiDiAdesione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_attiDiAdesione = FK_attiDiAdesione;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFK_attiDiAdesione() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("FK_attiDiAdesione"));
	}

	@Override
	public String getDescrizione() {
		if (_Descrizione == null) {
			return "";
		}
		else {
			return _Descrizione;
		}
	}

	@Override
	public void setDescrizione(String Descrizione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Descrizione = Descrizione;
	}

	@Override
	public String getStato() {
		if (_Stato == null) {
			return "";
		}
		else {
			return _Stato;
		}
	}

	@Override
	public void setStato(String Stato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Stato = Stato;
	}

	@Override
	public Date getDataStato() {
		return _DataStato;
	}

	@Override
	public void setDataStato(Date DataStato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataStato = DataStato;
	}

	@Override
	public Date getDataInizioFabbisogni() {
		return _DataInizioFabbisogni;
	}

	@Override
	public void setDataInizioFabbisogni(Date DataInizioFabbisogni) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataInizioFabbisogni = DataInizioFabbisogni;
	}

	@Override
	public Date getDataFineFabbisogni() {
		return _DataFineFabbisogni;
	}

	@Override
	public void setDataFineFabbisogni(Date DataFineFabbisogni) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataFineFabbisogni = DataFineFabbisogni;
	}

	@Override
	public String getUserIns() {
		if (_userIns == null) {
			return "";
		}
		else {
			return _userIns;
		}
	}

	@Override
	public void setUserIns(String userIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userIns = userIns;
	}

	@Override
	public String getUserAgg() {
		if (_userAgg == null) {
			return "";
		}
		else {
			return _userAgg;
		}
	}

	@Override
	public void setUserAgg(String userAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userAgg = userAgg;
	}

	@Override
	public Date getDataIns() {
		return _dataIns;
	}

	@Override
	public void setDataIns(Date dataIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataIns = dataIns;
	}

	@Override
	public Date getDataAgg() {
		return _dataAgg;
	}

	@Override
	public void setDataAgg(Date dataAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataAgg = dataAgg;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PianiFabbisogni.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PianiFabbisogni toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PianiFabbisogni>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PianiFabbisogniImpl pianiFabbisogniImpl = new PianiFabbisogniImpl();

		pianiFabbisogniImpl.setId_PianiFabbisogni(getId_PianiFabbisogni());
		pianiFabbisogniImpl.setCodicePianoFabbisogno(
			getCodicePianoFabbisogno());
		pianiFabbisogniImpl.setFK_documenti(getFK_documenti());
		pianiFabbisogniImpl.setFK_attiDiAdesione(getFK_attiDiAdesione());
		pianiFabbisogniImpl.setDescrizione(getDescrizione());
		pianiFabbisogniImpl.setStato(getStato());
		pianiFabbisogniImpl.setDataStato(getDataStato());
		pianiFabbisogniImpl.setDataInizioFabbisogni(getDataInizioFabbisogni());
		pianiFabbisogniImpl.setDataFineFabbisogni(getDataFineFabbisogni());
		pianiFabbisogniImpl.setUserIns(getUserIns());
		pianiFabbisogniImpl.setUserAgg(getUserAgg());
		pianiFabbisogniImpl.setDataIns(getDataIns());
		pianiFabbisogniImpl.setDataAgg(getDataAgg());

		pianiFabbisogniImpl.resetOriginalValues();

		return pianiFabbisogniImpl;
	}

	@Override
	public PianiFabbisogni cloneWithOriginalValues() {
		PianiFabbisogniImpl pianiFabbisogniImpl = new PianiFabbisogniImpl();

		pianiFabbisogniImpl.setId_PianiFabbisogni(
			this.<Long>getColumnOriginalValue("Id_PianiFabbisogni"));
		pianiFabbisogniImpl.setCodicePianoFabbisogno(
			this.<String>getColumnOriginalValue("CodicePianoFabbisogno"));
		pianiFabbisogniImpl.setFK_documenti(
			this.<Long>getColumnOriginalValue("FK_documenti"));
		pianiFabbisogniImpl.setFK_attiDiAdesione(
			this.<Long>getColumnOriginalValue("FK_attiDiAdesione"));
		pianiFabbisogniImpl.setDescrizione(
			this.<String>getColumnOriginalValue("Descrizione"));
		pianiFabbisogniImpl.setStato(
			this.<String>getColumnOriginalValue("Stato"));
		pianiFabbisogniImpl.setDataStato(
			this.<Date>getColumnOriginalValue("DataStato"));
		pianiFabbisogniImpl.setDataInizioFabbisogni(
			this.<Date>getColumnOriginalValue("DataInizioFabbisogni"));
		pianiFabbisogniImpl.setDataFineFabbisogni(
			this.<Date>getColumnOriginalValue("DataFineFabbisogni"));
		pianiFabbisogniImpl.setUserIns(
			this.<String>getColumnOriginalValue("userIns"));
		pianiFabbisogniImpl.setUserAgg(
			this.<String>getColumnOriginalValue("userAgg"));
		pianiFabbisogniImpl.setDataIns(
			this.<Date>getColumnOriginalValue("dataIns"));
		pianiFabbisogniImpl.setDataAgg(
			this.<Date>getColumnOriginalValue("dataAgg"));

		return pianiFabbisogniImpl;
	}

	@Override
	public int compareTo(PianiFabbisogni pianiFabbisogni) {
		long primaryKey = pianiFabbisogni.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PianiFabbisogni)) {
			return false;
		}

		PianiFabbisogni pianiFabbisogni = (PianiFabbisogni)object;

		long primaryKey = pianiFabbisogni.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PianiFabbisogni> toCacheModel() {
		PianiFabbisogniCacheModel pianiFabbisogniCacheModel =
			new PianiFabbisogniCacheModel();

		pianiFabbisogniCacheModel.Id_PianiFabbisogni = getId_PianiFabbisogni();

		pianiFabbisogniCacheModel.CodicePianoFabbisogno =
			getCodicePianoFabbisogno();

		String CodicePianoFabbisogno =
			pianiFabbisogniCacheModel.CodicePianoFabbisogno;

		if ((CodicePianoFabbisogno != null) &&
			(CodicePianoFabbisogno.length() == 0)) {

			pianiFabbisogniCacheModel.CodicePianoFabbisogno = null;
		}

		pianiFabbisogniCacheModel.FK_documenti = getFK_documenti();

		pianiFabbisogniCacheModel.FK_attiDiAdesione = getFK_attiDiAdesione();

		pianiFabbisogniCacheModel.Descrizione = getDescrizione();

		String Descrizione = pianiFabbisogniCacheModel.Descrizione;

		if ((Descrizione != null) && (Descrizione.length() == 0)) {
			pianiFabbisogniCacheModel.Descrizione = null;
		}

		pianiFabbisogniCacheModel.Stato = getStato();

		String Stato = pianiFabbisogniCacheModel.Stato;

		if ((Stato != null) && (Stato.length() == 0)) {
			pianiFabbisogniCacheModel.Stato = null;
		}

		Date DataStato = getDataStato();

		if (DataStato != null) {
			pianiFabbisogniCacheModel.DataStato = DataStato.getTime();
		}
		else {
			pianiFabbisogniCacheModel.DataStato = Long.MIN_VALUE;
		}

		Date DataInizioFabbisogni = getDataInizioFabbisogni();

		if (DataInizioFabbisogni != null) {
			pianiFabbisogniCacheModel.DataInizioFabbisogni =
				DataInizioFabbisogni.getTime();
		}
		else {
			pianiFabbisogniCacheModel.DataInizioFabbisogni = Long.MIN_VALUE;
		}

		Date DataFineFabbisogni = getDataFineFabbisogni();

		if (DataFineFabbisogni != null) {
			pianiFabbisogniCacheModel.DataFineFabbisogni =
				DataFineFabbisogni.getTime();
		}
		else {
			pianiFabbisogniCacheModel.DataFineFabbisogni = Long.MIN_VALUE;
		}

		pianiFabbisogniCacheModel.userIns = getUserIns();

		String userIns = pianiFabbisogniCacheModel.userIns;

		if ((userIns != null) && (userIns.length() == 0)) {
			pianiFabbisogniCacheModel.userIns = null;
		}

		pianiFabbisogniCacheModel.userAgg = getUserAgg();

		String userAgg = pianiFabbisogniCacheModel.userAgg;

		if ((userAgg != null) && (userAgg.length() == 0)) {
			pianiFabbisogniCacheModel.userAgg = null;
		}

		Date dataIns = getDataIns();

		if (dataIns != null) {
			pianiFabbisogniCacheModel.dataIns = dataIns.getTime();
		}
		else {
			pianiFabbisogniCacheModel.dataIns = Long.MIN_VALUE;
		}

		Date dataAgg = getDataAgg();

		if (dataAgg != null) {
			pianiFabbisogniCacheModel.dataAgg = dataAgg.getTime();
		}
		else {
			pianiFabbisogniCacheModel.dataAgg = Long.MIN_VALUE;
		}

		return pianiFabbisogniCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PianiFabbisogni, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PianiFabbisogni, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PianiFabbisogni, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PianiFabbisogni)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PianiFabbisogni, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PianiFabbisogni, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PianiFabbisogni, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PianiFabbisogni)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PianiFabbisogni>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PianiFabbisogni.class, ModelWrapper.class);

	}

	private long _Id_PianiFabbisogni;
	private String _CodicePianoFabbisogno;
	private long _FK_documenti;
	private long _FK_attiDiAdesione;
	private String _Descrizione;
	private String _Stato;
	private Date _DataStato;
	private Date _DataInizioFabbisogni;
	private Date _DataFineFabbisogni;
	private String _userIns;
	private String _userAgg;
	private Date _dataIns;
	private Date _dataAgg;

	public <T> T getColumnValue(String columnName) {
		Function<PianiFabbisogni, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PianiFabbisogni)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id_PianiFabbisogni", _Id_PianiFabbisogni);
		_columnOriginalValues.put(
			"CodicePianoFabbisogno", _CodicePianoFabbisogno);
		_columnOriginalValues.put("FK_documenti", _FK_documenti);
		_columnOriginalValues.put("FK_attiDiAdesione", _FK_attiDiAdesione);
		_columnOriginalValues.put("Descrizione", _Descrizione);
		_columnOriginalValues.put("Stato", _Stato);
		_columnOriginalValues.put("DataStato", _DataStato);
		_columnOriginalValues.put(
			"DataInizioFabbisogni", _DataInizioFabbisogni);
		_columnOriginalValues.put("DataFineFabbisogni", _DataFineFabbisogni);
		_columnOriginalValues.put("userIns", _userIns);
		_columnOriginalValues.put("userAgg", _userAgg);
		_columnOriginalValues.put("dataIns", _dataIns);
		_columnOriginalValues.put("dataAgg", _dataAgg);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id_PianiFabbisogni", 1L);

		columnBitmasks.put("CodicePianoFabbisogno", 2L);

		columnBitmasks.put("FK_documenti", 4L);

		columnBitmasks.put("FK_attiDiAdesione", 8L);

		columnBitmasks.put("Descrizione", 16L);

		columnBitmasks.put("Stato", 32L);

		columnBitmasks.put("DataStato", 64L);

		columnBitmasks.put("DataInizioFabbisogni", 128L);

		columnBitmasks.put("DataFineFabbisogni", 256L);

		columnBitmasks.put("userIns", 512L);

		columnBitmasks.put("userAgg", 1024L);

		columnBitmasks.put("dataIns", 2048L);

		columnBitmasks.put("dataAgg", 4096L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PianiFabbisogni _escapedModel;

}