/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import servicebuilder.model.PianiSubentro;
import servicebuilder.model.PianiSubentroModel;

/**
 * The base model implementation for the PianiSubentro service. Represents a row in the &quot;AQ_PianiSubentro&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PianiSubentroModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PianiSubentroImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PianiSubentroImpl
 * @generated
 */
public class PianiSubentroModelImpl
	extends BaseModelImpl<PianiSubentro> implements PianiSubentroModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a piani subentro model instance should use the <code>PianiSubentro</code> interface instead.
	 */
	public static final String TABLE_NAME = "AQ_PianiSubentro";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id_PianiSubentro", Types.BIGINT},
		{"CodicePianiDiSubentro", Types.VARCHAR},
		{"FK_documenti", Types.BIGINT}, {"FK_accordoQuadro", Types.BIGINT},
		{"Descrizione", Types.VARCHAR}, {"DataInizioPiano", Types.TIMESTAMP},
		{"DataFinePiano", Types.TIMESTAMP}, {"userIns", Types.VARCHAR},
		{"userAgg", Types.VARCHAR}, {"dataIns", Types.TIMESTAMP},
		{"dataAgg", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id_PianiSubentro", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CodicePianiDiSubentro", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FK_documenti", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FK_accordoQuadro", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Descrizione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DataInizioPiano", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("DataFinePiano", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userIns", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userAgg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataIns", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataAgg", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AQ_PianiSubentro (Id_PianiSubentro LONG not null primary key,CodicePianiDiSubentro VARCHAR(75) null,FK_documenti LONG,FK_accordoQuadro LONG,Descrizione VARCHAR(75) null,DataInizioPiano DATE null,DataFinePiano DATE null,userIns VARCHAR(75) null,userAgg VARCHAR(75) null,dataIns DATE null,dataAgg DATE null)";

	public static final String TABLE_SQL_DROP = "drop table AQ_PianiSubentro";

	public static final String ORDER_BY_JPQL =
		" ORDER BY pianiSubentro.Id_PianiSubentro ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AQ_PianiSubentro.Id_PianiSubentro ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_PIANISUBENTRO_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PianiSubentroModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id_PianiSubentro;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_PianiSubentro(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id_PianiSubentro;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PianiSubentro.class;
	}

	@Override
	public String getModelClassName() {
		return PianiSubentro.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PianiSubentro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PianiSubentro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PianiSubentro, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PianiSubentro)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PianiSubentro, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PianiSubentro, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PianiSubentro)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PianiSubentro, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PianiSubentro, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<PianiSubentro, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PianiSubentro, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PianiSubentro, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<PianiSubentro, Object>>();
		Map<String, BiConsumer<PianiSubentro, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PianiSubentro, ?>>();

		attributeGetterFunctions.put(
			"Id_PianiSubentro", PianiSubentro::getId_PianiSubentro);
		attributeSetterBiConsumers.put(
			"Id_PianiSubentro",
			(BiConsumer<PianiSubentro, Long>)
				PianiSubentro::setId_PianiSubentro);
		attributeGetterFunctions.put(
			"CodicePianiDiSubentro", PianiSubentro::getCodicePianiDiSubentro);
		attributeSetterBiConsumers.put(
			"CodicePianiDiSubentro",
			(BiConsumer<PianiSubentro, String>)
				PianiSubentro::setCodicePianiDiSubentro);
		attributeGetterFunctions.put(
			"FK_documenti", PianiSubentro::getFK_documenti);
		attributeSetterBiConsumers.put(
			"FK_documenti",
			(BiConsumer<PianiSubentro, Long>)PianiSubentro::setFK_documenti);
		attributeGetterFunctions.put(
			"FK_accordoQuadro", PianiSubentro::getFK_accordoQuadro);
		attributeSetterBiConsumers.put(
			"FK_accordoQuadro",
			(BiConsumer<PianiSubentro, Long>)
				PianiSubentro::setFK_accordoQuadro);
		attributeGetterFunctions.put(
			"Descrizione", PianiSubentro::getDescrizione);
		attributeSetterBiConsumers.put(
			"Descrizione",
			(BiConsumer<PianiSubentro, String>)PianiSubentro::setDescrizione);
		attributeGetterFunctions.put(
			"DataInizioPiano", PianiSubentro::getDataInizioPiano);
		attributeSetterBiConsumers.put(
			"DataInizioPiano",
			(BiConsumer<PianiSubentro, Date>)PianiSubentro::setDataInizioPiano);
		attributeGetterFunctions.put(
			"DataFinePiano", PianiSubentro::getDataFinePiano);
		attributeSetterBiConsumers.put(
			"DataFinePiano",
			(BiConsumer<PianiSubentro, Date>)PianiSubentro::setDataFinePiano);
		attributeGetterFunctions.put("userIns", PianiSubentro::getUserIns);
		attributeSetterBiConsumers.put(
			"userIns",
			(BiConsumer<PianiSubentro, String>)PianiSubentro::setUserIns);
		attributeGetterFunctions.put("userAgg", PianiSubentro::getUserAgg);
		attributeSetterBiConsumers.put(
			"userAgg",
			(BiConsumer<PianiSubentro, String>)PianiSubentro::setUserAgg);
		attributeGetterFunctions.put("dataIns", PianiSubentro::getDataIns);
		attributeSetterBiConsumers.put(
			"dataIns",
			(BiConsumer<PianiSubentro, Date>)PianiSubentro::setDataIns);
		attributeGetterFunctions.put("dataAgg", PianiSubentro::getDataAgg);
		attributeSetterBiConsumers.put(
			"dataAgg",
			(BiConsumer<PianiSubentro, Date>)PianiSubentro::setDataAgg);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId_PianiSubentro() {
		return _Id_PianiSubentro;
	}

	@Override
	public void setId_PianiSubentro(long Id_PianiSubentro) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id_PianiSubentro = Id_PianiSubentro;
	}

	@Override
	public String getCodicePianiDiSubentro() {
		if (_CodicePianiDiSubentro == null) {
			return "";
		}
		else {
			return _CodicePianiDiSubentro;
		}
	}

	@Override
	public void setCodicePianiDiSubentro(String CodicePianiDiSubentro) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CodicePianiDiSubentro = CodicePianiDiSubentro;
	}

	@Override
	public long getFK_documenti() {
		return _FK_documenti;
	}

	@Override
	public void setFK_documenti(long FK_documenti) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_documenti = FK_documenti;
	}

	@Override
	public long getFK_accordoQuadro() {
		return _FK_accordoQuadro;
	}

	@Override
	public void setFK_accordoQuadro(long FK_accordoQuadro) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_accordoQuadro = FK_accordoQuadro;
	}

	@Override
	public String getDescrizione() {
		if (_Descrizione == null) {
			return "";
		}
		else {
			return _Descrizione;
		}
	}

	@Override
	public void setDescrizione(String Descrizione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Descrizione = Descrizione;
	}

	@Override
	public Date getDataInizioPiano() {
		return _DataInizioPiano;
	}

	@Override
	public void setDataInizioPiano(Date DataInizioPiano) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataInizioPiano = DataInizioPiano;
	}

	@Override
	public Date getDataFinePiano() {
		return _DataFinePiano;
	}

	@Override
	public void setDataFinePiano(Date DataFinePiano) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataFinePiano = DataFinePiano;
	}

	@Override
	public String getUserIns() {
		if (_userIns == null) {
			return "";
		}
		else {
			return _userIns;
		}
	}

	@Override
	public void setUserIns(String userIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userIns = userIns;
	}

	@Override
	public String getUserAgg() {
		if (_userAgg == null) {
			return "";
		}
		else {
			return _userAgg;
		}
	}

	@Override
	public void setUserAgg(String userAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userAgg = userAgg;
	}

	@Override
	public Date getDataIns() {
		return _dataIns;
	}

	@Override
	public void setDataIns(Date dataIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataIns = dataIns;
	}

	@Override
	public Date getDataAgg() {
		return _dataAgg;
	}

	@Override
	public void setDataAgg(Date dataAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataAgg = dataAgg;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PianiSubentro.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PianiSubentro toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PianiSubentro>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PianiSubentroImpl pianiSubentroImpl = new PianiSubentroImpl();

		pianiSubentroImpl.setId_PianiSubentro(getId_PianiSubentro());
		pianiSubentroImpl.setCodicePianiDiSubentro(getCodicePianiDiSubentro());
		pianiSubentroImpl.setFK_documenti(getFK_documenti());
		pianiSubentroImpl.setFK_accordoQuadro(getFK_accordoQuadro());
		pianiSubentroImpl.setDescrizione(getDescrizione());
		pianiSubentroImpl.setDataInizioPiano(getDataInizioPiano());
		pianiSubentroImpl.setDataFinePiano(getDataFinePiano());
		pianiSubentroImpl.setUserIns(getUserIns());
		pianiSubentroImpl.setUserAgg(getUserAgg());
		pianiSubentroImpl.setDataIns(getDataIns());
		pianiSubentroImpl.setDataAgg(getDataAgg());

		pianiSubentroImpl.resetOriginalValues();

		return pianiSubentroImpl;
	}

	@Override
	public PianiSubentro cloneWithOriginalValues() {
		PianiSubentroImpl pianiSubentroImpl = new PianiSubentroImpl();

		pianiSubentroImpl.setId_PianiSubentro(
			this.<Long>getColumnOriginalValue("Id_PianiSubentro"));
		pianiSubentroImpl.setCodicePianiDiSubentro(
			this.<String>getColumnOriginalValue("CodicePianiDiSubentro"));
		pianiSubentroImpl.setFK_documenti(
			this.<Long>getColumnOriginalValue("FK_documenti"));
		pianiSubentroImpl.setFK_accordoQuadro(
			this.<Long>getColumnOriginalValue("FK_accordoQuadro"));
		pianiSubentroImpl.setDescrizione(
			this.<String>getColumnOriginalValue("Descrizione"));
		pianiSubentroImpl.setDataInizioPiano(
			this.<Date>getColumnOriginalValue("DataInizioPiano"));
		pianiSubentroImpl.setDataFinePiano(
			this.<Date>getColumnOriginalValue("DataFinePiano"));
		pianiSubentroImpl.setUserIns(
			this.<String>getColumnOriginalValue("userIns"));
		pianiSubentroImpl.setUserAgg(
			this.<String>getColumnOriginalValue("userAgg"));
		pianiSubentroImpl.setDataIns(
			this.<Date>getColumnOriginalValue("dataIns"));
		pianiSubentroImpl.setDataAgg(
			this.<Date>getColumnOriginalValue("dataAgg"));

		return pianiSubentroImpl;
	}

	@Override
	public int compareTo(PianiSubentro pianiSubentro) {
		long primaryKey = pianiSubentro.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PianiSubentro)) {
			return false;
		}

		PianiSubentro pianiSubentro = (PianiSubentro)object;

		long primaryKey = pianiSubentro.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PianiSubentro> toCacheModel() {
		PianiSubentroCacheModel pianiSubentroCacheModel =
			new PianiSubentroCacheModel();

		pianiSubentroCacheModel.Id_PianiSubentro = getId_PianiSubentro();

		pianiSubentroCacheModel.CodicePianiDiSubentro =
			getCodicePianiDiSubentro();

		String CodicePianiDiSubentro =
			pianiSubentroCacheModel.CodicePianiDiSubentro;

		if ((CodicePianiDiSubentro != null) &&
			(CodicePianiDiSubentro.length() == 0)) {

			pianiSubentroCacheModel.CodicePianiDiSubentro = null;
		}

		pianiSubentroCacheModel.FK_documenti = getFK_documenti();

		pianiSubentroCacheModel.FK_accordoQuadro = getFK_accordoQuadro();

		pianiSubentroCacheModel.Descrizione = getDescrizione();

		String Descrizione = pianiSubentroCacheModel.Descrizione;

		if ((Descrizione != null) && (Descrizione.length() == 0)) {
			pianiSubentroCacheModel.Descrizione = null;
		}

		Date DataInizioPiano = getDataInizioPiano();

		if (DataInizioPiano != null) {
			pianiSubentroCacheModel.DataInizioPiano = DataInizioPiano.getTime();
		}
		else {
			pianiSubentroCacheModel.DataInizioPiano = Long.MIN_VALUE;
		}

		Date DataFinePiano = getDataFinePiano();

		if (DataFinePiano != null) {
			pianiSubentroCacheModel.DataFinePiano = DataFinePiano.getTime();
		}
		else {
			pianiSubentroCacheModel.DataFinePiano = Long.MIN_VALUE;
		}

		pianiSubentroCacheModel.userIns = getUserIns();

		String userIns = pianiSubentroCacheModel.userIns;

		if ((userIns != null) && (userIns.length() == 0)) {
			pianiSubentroCacheModel.userIns = null;
		}

		pianiSubentroCacheModel.userAgg = getUserAgg();

		String userAgg = pianiSubentroCacheModel.userAgg;

		if ((userAgg != null) && (userAgg.length() == 0)) {
			pianiSubentroCacheModel.userAgg = null;
		}

		Date dataIns = getDataIns();

		if (dataIns != null) {
			pianiSubentroCacheModel.dataIns = dataIns.getTime();
		}
		else {
			pianiSubentroCacheModel.dataIns = Long.MIN_VALUE;
		}

		Date dataAgg = getDataAgg();

		if (dataAgg != null) {
			pianiSubentroCacheModel.dataAgg = dataAgg.getTime();
		}
		else {
			pianiSubentroCacheModel.dataAgg = Long.MIN_VALUE;
		}

		return pianiSubentroCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PianiSubentro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PianiSubentro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PianiSubentro, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PianiSubentro)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PianiSubentro, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PianiSubentro, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PianiSubentro, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PianiSubentro)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PianiSubentro>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PianiSubentro.class, ModelWrapper.class);

	}

	private long _Id_PianiSubentro;
	private String _CodicePianiDiSubentro;
	private long _FK_documenti;
	private long _FK_accordoQuadro;
	private String _Descrizione;
	private Date _DataInizioPiano;
	private Date _DataFinePiano;
	private String _userIns;
	private String _userAgg;
	private Date _dataIns;
	private Date _dataAgg;

	public <T> T getColumnValue(String columnName) {
		Function<PianiSubentro, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PianiSubentro)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id_PianiSubentro", _Id_PianiSubentro);
		_columnOriginalValues.put(
			"CodicePianiDiSubentro", _CodicePianiDiSubentro);
		_columnOriginalValues.put("FK_documenti", _FK_documenti);
		_columnOriginalValues.put("FK_accordoQuadro", _FK_accordoQuadro);
		_columnOriginalValues.put("Descrizione", _Descrizione);
		_columnOriginalValues.put("DataInizioPiano", _DataInizioPiano);
		_columnOriginalValues.put("DataFinePiano", _DataFinePiano);
		_columnOriginalValues.put("userIns", _userIns);
		_columnOriginalValues.put("userAgg", _userAgg);
		_columnOriginalValues.put("dataIns", _dataIns);
		_columnOriginalValues.put("dataAgg", _dataAgg);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id_PianiSubentro", 1L);

		columnBitmasks.put("CodicePianiDiSubentro", 2L);

		columnBitmasks.put("FK_documenti", 4L);

		columnBitmasks.put("FK_accordoQuadro", 8L);

		columnBitmasks.put("Descrizione", 16L);

		columnBitmasks.put("DataInizioPiano", 32L);

		columnBitmasks.put("DataFinePiano", 64L);

		columnBitmasks.put("userIns", 128L);

		columnBitmasks.put("userAgg", 256L);

		columnBitmasks.put("dataIns", 512L);

		columnBitmasks.put("dataAgg", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PianiSubentro _escapedModel;

}