/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import servicebuilder.model.PianiDeiRischi;
import servicebuilder.model.PianiDeiRischiModel;

/**
 * The base model implementation for the PianiDeiRischi service. Represents a row in the &quot;AQ_PianiDeiRischi&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PianiDeiRischiModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PianiDeiRischiImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PianiDeiRischiImpl
 * @generated
 */
public class PianiDeiRischiModelImpl
	extends BaseModelImpl<PianiDeiRischi> implements PianiDeiRischiModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a piani dei rischi model instance should use the <code>PianiDeiRischi</code> interface instead.
	 */
	public static final String TABLE_NAME = "AQ_PianiDeiRischi";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id_PianiDeiRischi", Types.BIGINT},
		{"CodicePianoDeiRischi", Types.VARCHAR}, {"FK_documenti", Types.BIGINT},
		{"FK_accordoQuadro", Types.BIGINT}, {"Descrizione", Types.VARCHAR},
		{"DataInizioPiano", Types.TIMESTAMP},
		{"DataFinePiano", Types.TIMESTAMP}, {"userIns", Types.VARCHAR},
		{"userAgg", Types.VARCHAR}, {"dataIns", Types.TIMESTAMP},
		{"dataAgg", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id_PianiDeiRischi", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CodicePianoDeiRischi", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FK_documenti", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FK_accordoQuadro", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Descrizione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DataInizioPiano", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("DataFinePiano", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userIns", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userAgg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataIns", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataAgg", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AQ_PianiDeiRischi (Id_PianiDeiRischi LONG not null primary key,CodicePianoDeiRischi VARCHAR(75) null,FK_documenti LONG,FK_accordoQuadro LONG,Descrizione VARCHAR(75) null,DataInizioPiano DATE null,DataFinePiano DATE null,userIns VARCHAR(75) null,userAgg VARCHAR(75) null,dataIns DATE null,dataAgg DATE null)";

	public static final String TABLE_SQL_DROP = "drop table AQ_PianiDeiRischi";

	public static final String ORDER_BY_JPQL =
		" ORDER BY pianiDeiRischi.Id_PianiDeiRischi ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AQ_PianiDeiRischi.Id_PianiDeiRischi ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_PIANIDEIRISCHI_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PianiDeiRischiModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id_PianiDeiRischi;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_PianiDeiRischi(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id_PianiDeiRischi;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PianiDeiRischi.class;
	}

	@Override
	public String getModelClassName() {
		return PianiDeiRischi.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PianiDeiRischi, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PianiDeiRischi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PianiDeiRischi, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PianiDeiRischi)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PianiDeiRischi, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PianiDeiRischi, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PianiDeiRischi)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PianiDeiRischi, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PianiDeiRischi, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<PianiDeiRischi, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PianiDeiRischi, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PianiDeiRischi, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<PianiDeiRischi, Object>>();
		Map<String, BiConsumer<PianiDeiRischi, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PianiDeiRischi, ?>>();

		attributeGetterFunctions.put(
			"Id_PianiDeiRischi", PianiDeiRischi::getId_PianiDeiRischi);
		attributeSetterBiConsumers.put(
			"Id_PianiDeiRischi",
			(BiConsumer<PianiDeiRischi, Long>)
				PianiDeiRischi::setId_PianiDeiRischi);
		attributeGetterFunctions.put(
			"CodicePianoDeiRischi", PianiDeiRischi::getCodicePianoDeiRischi);
		attributeSetterBiConsumers.put(
			"CodicePianoDeiRischi",
			(BiConsumer<PianiDeiRischi, String>)
				PianiDeiRischi::setCodicePianoDeiRischi);
		attributeGetterFunctions.put(
			"FK_documenti", PianiDeiRischi::getFK_documenti);
		attributeSetterBiConsumers.put(
			"FK_documenti",
			(BiConsumer<PianiDeiRischi, Long>)PianiDeiRischi::setFK_documenti);
		attributeGetterFunctions.put(
			"FK_accordoQuadro", PianiDeiRischi::getFK_accordoQuadro);
		attributeSetterBiConsumers.put(
			"FK_accordoQuadro",
			(BiConsumer<PianiDeiRischi, Long>)
				PianiDeiRischi::setFK_accordoQuadro);
		attributeGetterFunctions.put(
			"Descrizione", PianiDeiRischi::getDescrizione);
		attributeSetterBiConsumers.put(
			"Descrizione",
			(BiConsumer<PianiDeiRischi, String>)PianiDeiRischi::setDescrizione);
		attributeGetterFunctions.put(
			"DataInizioPiano", PianiDeiRischi::getDataInizioPiano);
		attributeSetterBiConsumers.put(
			"DataInizioPiano",
			(BiConsumer<PianiDeiRischi, Date>)
				PianiDeiRischi::setDataInizioPiano);
		attributeGetterFunctions.put(
			"DataFinePiano", PianiDeiRischi::getDataFinePiano);
		attributeSetterBiConsumers.put(
			"DataFinePiano",
			(BiConsumer<PianiDeiRischi, Date>)PianiDeiRischi::setDataFinePiano);
		attributeGetterFunctions.put("userIns", PianiDeiRischi::getUserIns);
		attributeSetterBiConsumers.put(
			"userIns",
			(BiConsumer<PianiDeiRischi, String>)PianiDeiRischi::setUserIns);
		attributeGetterFunctions.put("userAgg", PianiDeiRischi::getUserAgg);
		attributeSetterBiConsumers.put(
			"userAgg",
			(BiConsumer<PianiDeiRischi, String>)PianiDeiRischi::setUserAgg);
		attributeGetterFunctions.put("dataIns", PianiDeiRischi::getDataIns);
		attributeSetterBiConsumers.put(
			"dataIns",
			(BiConsumer<PianiDeiRischi, Date>)PianiDeiRischi::setDataIns);
		attributeGetterFunctions.put("dataAgg", PianiDeiRischi::getDataAgg);
		attributeSetterBiConsumers.put(
			"dataAgg",
			(BiConsumer<PianiDeiRischi, Date>)PianiDeiRischi::setDataAgg);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId_PianiDeiRischi() {
		return _Id_PianiDeiRischi;
	}

	@Override
	public void setId_PianiDeiRischi(long Id_PianiDeiRischi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id_PianiDeiRischi = Id_PianiDeiRischi;
	}

	@Override
	public String getCodicePianoDeiRischi() {
		if (_CodicePianoDeiRischi == null) {
			return "";
		}
		else {
			return _CodicePianoDeiRischi;
		}
	}

	@Override
	public void setCodicePianoDeiRischi(String CodicePianoDeiRischi) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CodicePianoDeiRischi = CodicePianoDeiRischi;
	}

	@Override
	public long getFK_documenti() {
		return _FK_documenti;
	}

	@Override
	public void setFK_documenti(long FK_documenti) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_documenti = FK_documenti;
	}

	@Override
	public long getFK_accordoQuadro() {
		return _FK_accordoQuadro;
	}

	@Override
	public void setFK_accordoQuadro(long FK_accordoQuadro) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_accordoQuadro = FK_accordoQuadro;
	}

	@Override
	public String getDescrizione() {
		if (_Descrizione == null) {
			return "";
		}
		else {
			return _Descrizione;
		}
	}

	@Override
	public void setDescrizione(String Descrizione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Descrizione = Descrizione;
	}

	@Override
	public Date getDataInizioPiano() {
		return _DataInizioPiano;
	}

	@Override
	public void setDataInizioPiano(Date DataInizioPiano) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataInizioPiano = DataInizioPiano;
	}

	@Override
	public Date getDataFinePiano() {
		return _DataFinePiano;
	}

	@Override
	public void setDataFinePiano(Date DataFinePiano) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataFinePiano = DataFinePiano;
	}

	@Override
	public String getUserIns() {
		if (_userIns == null) {
			return "";
		}
		else {
			return _userIns;
		}
	}

	@Override
	public void setUserIns(String userIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userIns = userIns;
	}

	@Override
	public String getUserAgg() {
		if (_userAgg == null) {
			return "";
		}
		else {
			return _userAgg;
		}
	}

	@Override
	public void setUserAgg(String userAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userAgg = userAgg;
	}

	@Override
	public Date getDataIns() {
		return _dataIns;
	}

	@Override
	public void setDataIns(Date dataIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataIns = dataIns;
	}

	@Override
	public Date getDataAgg() {
		return _dataAgg;
	}

	@Override
	public void setDataAgg(Date dataAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataAgg = dataAgg;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PianiDeiRischi.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PianiDeiRischi toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PianiDeiRischi>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PianiDeiRischiImpl pianiDeiRischiImpl = new PianiDeiRischiImpl();

		pianiDeiRischiImpl.setId_PianiDeiRischi(getId_PianiDeiRischi());
		pianiDeiRischiImpl.setCodicePianoDeiRischi(getCodicePianoDeiRischi());
		pianiDeiRischiImpl.setFK_documenti(getFK_documenti());
		pianiDeiRischiImpl.setFK_accordoQuadro(getFK_accordoQuadro());
		pianiDeiRischiImpl.setDescrizione(getDescrizione());
		pianiDeiRischiImpl.setDataInizioPiano(getDataInizioPiano());
		pianiDeiRischiImpl.setDataFinePiano(getDataFinePiano());
		pianiDeiRischiImpl.setUserIns(getUserIns());
		pianiDeiRischiImpl.setUserAgg(getUserAgg());
		pianiDeiRischiImpl.setDataIns(getDataIns());
		pianiDeiRischiImpl.setDataAgg(getDataAgg());

		pianiDeiRischiImpl.resetOriginalValues();

		return pianiDeiRischiImpl;
	}

	@Override
	public PianiDeiRischi cloneWithOriginalValues() {
		PianiDeiRischiImpl pianiDeiRischiImpl = new PianiDeiRischiImpl();

		pianiDeiRischiImpl.setId_PianiDeiRischi(
			this.<Long>getColumnOriginalValue("Id_PianiDeiRischi"));
		pianiDeiRischiImpl.setCodicePianoDeiRischi(
			this.<String>getColumnOriginalValue("CodicePianoDeiRischi"));
		pianiDeiRischiImpl.setFK_documenti(
			this.<Long>getColumnOriginalValue("FK_documenti"));
		pianiDeiRischiImpl.setFK_accordoQuadro(
			this.<Long>getColumnOriginalValue("FK_accordoQuadro"));
		pianiDeiRischiImpl.setDescrizione(
			this.<String>getColumnOriginalValue("Descrizione"));
		pianiDeiRischiImpl.setDataInizioPiano(
			this.<Date>getColumnOriginalValue("DataInizioPiano"));
		pianiDeiRischiImpl.setDataFinePiano(
			this.<Date>getColumnOriginalValue("DataFinePiano"));
		pianiDeiRischiImpl.setUserIns(
			this.<String>getColumnOriginalValue("userIns"));
		pianiDeiRischiImpl.setUserAgg(
			this.<String>getColumnOriginalValue("userAgg"));
		pianiDeiRischiImpl.setDataIns(
			this.<Date>getColumnOriginalValue("dataIns"));
		pianiDeiRischiImpl.setDataAgg(
			this.<Date>getColumnOriginalValue("dataAgg"));

		return pianiDeiRischiImpl;
	}

	@Override
	public int compareTo(PianiDeiRischi pianiDeiRischi) {
		long primaryKey = pianiDeiRischi.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PianiDeiRischi)) {
			return false;
		}

		PianiDeiRischi pianiDeiRischi = (PianiDeiRischi)object;

		long primaryKey = pianiDeiRischi.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PianiDeiRischi> toCacheModel() {
		PianiDeiRischiCacheModel pianiDeiRischiCacheModel =
			new PianiDeiRischiCacheModel();

		pianiDeiRischiCacheModel.Id_PianiDeiRischi = getId_PianiDeiRischi();

		pianiDeiRischiCacheModel.CodicePianoDeiRischi =
			getCodicePianoDeiRischi();

		String CodicePianoDeiRischi =
			pianiDeiRischiCacheModel.CodicePianoDeiRischi;

		if ((CodicePianoDeiRischi != null) &&
			(CodicePianoDeiRischi.length() == 0)) {

			pianiDeiRischiCacheModel.CodicePianoDeiRischi = null;
		}

		pianiDeiRischiCacheModel.FK_documenti = getFK_documenti();

		pianiDeiRischiCacheModel.FK_accordoQuadro = getFK_accordoQuadro();

		pianiDeiRischiCacheModel.Descrizione = getDescrizione();

		String Descrizione = pianiDeiRischiCacheModel.Descrizione;

		if ((Descrizione != null) && (Descrizione.length() == 0)) {
			pianiDeiRischiCacheModel.Descrizione = null;
		}

		Date DataInizioPiano = getDataInizioPiano();

		if (DataInizioPiano != null) {
			pianiDeiRischiCacheModel.DataInizioPiano =
				DataInizioPiano.getTime();
		}
		else {
			pianiDeiRischiCacheModel.DataInizioPiano = Long.MIN_VALUE;
		}

		Date DataFinePiano = getDataFinePiano();

		if (DataFinePiano != null) {
			pianiDeiRischiCacheModel.DataFinePiano = DataFinePiano.getTime();
		}
		else {
			pianiDeiRischiCacheModel.DataFinePiano = Long.MIN_VALUE;
		}

		pianiDeiRischiCacheModel.userIns = getUserIns();

		String userIns = pianiDeiRischiCacheModel.userIns;

		if ((userIns != null) && (userIns.length() == 0)) {
			pianiDeiRischiCacheModel.userIns = null;
		}

		pianiDeiRischiCacheModel.userAgg = getUserAgg();

		String userAgg = pianiDeiRischiCacheModel.userAgg;

		if ((userAgg != null) && (userAgg.length() == 0)) {
			pianiDeiRischiCacheModel.userAgg = null;
		}

		Date dataIns = getDataIns();

		if (dataIns != null) {
			pianiDeiRischiCacheModel.dataIns = dataIns.getTime();
		}
		else {
			pianiDeiRischiCacheModel.dataIns = Long.MIN_VALUE;
		}

		Date dataAgg = getDataAgg();

		if (dataAgg != null) {
			pianiDeiRischiCacheModel.dataAgg = dataAgg.getTime();
		}
		else {
			pianiDeiRischiCacheModel.dataAgg = Long.MIN_VALUE;
		}

		return pianiDeiRischiCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PianiDeiRischi, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PianiDeiRischi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PianiDeiRischi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PianiDeiRischi)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PianiDeiRischi, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PianiDeiRischi, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PianiDeiRischi, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PianiDeiRischi)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PianiDeiRischi>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PianiDeiRischi.class, ModelWrapper.class);

	}

	private long _Id_PianiDeiRischi;
	private String _CodicePianoDeiRischi;
	private long _FK_documenti;
	private long _FK_accordoQuadro;
	private String _Descrizione;
	private Date _DataInizioPiano;
	private Date _DataFinePiano;
	private String _userIns;
	private String _userAgg;
	private Date _dataIns;
	private Date _dataAgg;

	public <T> T getColumnValue(String columnName) {
		Function<PianiDeiRischi, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PianiDeiRischi)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id_PianiDeiRischi", _Id_PianiDeiRischi);
		_columnOriginalValues.put(
			"CodicePianoDeiRischi", _CodicePianoDeiRischi);
		_columnOriginalValues.put("FK_documenti", _FK_documenti);
		_columnOriginalValues.put("FK_accordoQuadro", _FK_accordoQuadro);
		_columnOriginalValues.put("Descrizione", _Descrizione);
		_columnOriginalValues.put("DataInizioPiano", _DataInizioPiano);
		_columnOriginalValues.put("DataFinePiano", _DataFinePiano);
		_columnOriginalValues.put("userIns", _userIns);
		_columnOriginalValues.put("userAgg", _userAgg);
		_columnOriginalValues.put("dataIns", _dataIns);
		_columnOriginalValues.put("dataAgg", _dataAgg);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id_PianiDeiRischi", 1L);

		columnBitmasks.put("CodicePianoDeiRischi", 2L);

		columnBitmasks.put("FK_documenti", 4L);

		columnBitmasks.put("FK_accordoQuadro", 8L);

		columnBitmasks.put("Descrizione", 16L);

		columnBitmasks.put("DataInizioPiano", 32L);

		columnBitmasks.put("DataFinePiano", 64L);

		columnBitmasks.put("userIns", 128L);

		columnBitmasks.put("userAgg", 256L);

		columnBitmasks.put("dataIns", 512L);

		columnBitmasks.put("dataAgg", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PianiDeiRischi _escapedModel;

}