/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import servicebuilder.model.PianiDiQualita;
import servicebuilder.model.PianiDiQualitaModel;

/**
 * The base model implementation for the PianiDiQualita service. Represents a row in the &quot;AQ_PianiDiQualita&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>PianiDiQualitaModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link PianiDiQualitaImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see PianiDiQualitaImpl
 * @generated
 */
public class PianiDiQualitaModelImpl
	extends BaseModelImpl<PianiDiQualita> implements PianiDiQualitaModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a piani di qualita model instance should use the <code>PianiDiQualita</code> interface instead.
	 */
	public static final String TABLE_NAME = "AQ_PianiDiQualita";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id_PianiDiQualita", Types.BIGINT},
		{"CodicePianoDiQualita", Types.VARCHAR}, {"FK_documenti", Types.BIGINT},
		{"FK_accordoQuadro", Types.BIGINT}, {"Descrizione", Types.VARCHAR},
		{"DataInizioPiano", Types.TIMESTAMP},
		{"DataFinePiano", Types.TIMESTAMP}, {"userIns", Types.VARCHAR},
		{"userAgg", Types.VARCHAR}, {"dataIns", Types.TIMESTAMP},
		{"dataAgg", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id_PianiDiQualita", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CodicePianoDiQualita", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FK_documenti", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FK_accordoQuadro", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Descrizione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DataInizioPiano", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("DataFinePiano", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userIns", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userAgg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataIns", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataAgg", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AQ_PianiDiQualita (Id_PianiDiQualita LONG not null primary key,CodicePianoDiQualita VARCHAR(75) null,FK_documenti LONG,FK_accordoQuadro LONG,Descrizione VARCHAR(75) null,DataInizioPiano DATE null,DataFinePiano DATE null,userIns VARCHAR(75) null,userAgg VARCHAR(75) null,dataIns DATE null,dataAgg DATE null)";

	public static final String TABLE_SQL_DROP = "drop table AQ_PianiDiQualita";

	public static final String ORDER_BY_JPQL =
		" ORDER BY pianiDiQualita.Id_PianiDiQualita ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AQ_PianiDiQualita.Id_PianiDiQualita ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_PIANIDIQUALITA_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public PianiDiQualitaModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id_PianiDiQualita;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_PianiDiQualita(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id_PianiDiQualita;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return PianiDiQualita.class;
	}

	@Override
	public String getModelClassName() {
		return PianiDiQualita.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<PianiDiQualita, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<PianiDiQualita, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PianiDiQualita, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((PianiDiQualita)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<PianiDiQualita, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<PianiDiQualita, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(PianiDiQualita)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<PianiDiQualita, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<PianiDiQualita, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<PianiDiQualita, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<PianiDiQualita, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<PianiDiQualita, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<PianiDiQualita, Object>>();
		Map<String, BiConsumer<PianiDiQualita, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<PianiDiQualita, ?>>();

		attributeGetterFunctions.put(
			"Id_PianiDiQualita", PianiDiQualita::getId_PianiDiQualita);
		attributeSetterBiConsumers.put(
			"Id_PianiDiQualita",
			(BiConsumer<PianiDiQualita, Long>)
				PianiDiQualita::setId_PianiDiQualita);
		attributeGetterFunctions.put(
			"CodicePianoDiQualita", PianiDiQualita::getCodicePianoDiQualita);
		attributeSetterBiConsumers.put(
			"CodicePianoDiQualita",
			(BiConsumer<PianiDiQualita, String>)
				PianiDiQualita::setCodicePianoDiQualita);
		attributeGetterFunctions.put(
			"FK_documenti", PianiDiQualita::getFK_documenti);
		attributeSetterBiConsumers.put(
			"FK_documenti",
			(BiConsumer<PianiDiQualita, Long>)PianiDiQualita::setFK_documenti);
		attributeGetterFunctions.put(
			"FK_accordoQuadro", PianiDiQualita::getFK_accordoQuadro);
		attributeSetterBiConsumers.put(
			"FK_accordoQuadro",
			(BiConsumer<PianiDiQualita, Long>)
				PianiDiQualita::setFK_accordoQuadro);
		attributeGetterFunctions.put(
			"Descrizione", PianiDiQualita::getDescrizione);
		attributeSetterBiConsumers.put(
			"Descrizione",
			(BiConsumer<PianiDiQualita, String>)PianiDiQualita::setDescrizione);
		attributeGetterFunctions.put(
			"DataInizioPiano", PianiDiQualita::getDataInizioPiano);
		attributeSetterBiConsumers.put(
			"DataInizioPiano",
			(BiConsumer<PianiDiQualita, Date>)
				PianiDiQualita::setDataInizioPiano);
		attributeGetterFunctions.put(
			"DataFinePiano", PianiDiQualita::getDataFinePiano);
		attributeSetterBiConsumers.put(
			"DataFinePiano",
			(BiConsumer<PianiDiQualita, Date>)PianiDiQualita::setDataFinePiano);
		attributeGetterFunctions.put("userIns", PianiDiQualita::getUserIns);
		attributeSetterBiConsumers.put(
			"userIns",
			(BiConsumer<PianiDiQualita, String>)PianiDiQualita::setUserIns);
		attributeGetterFunctions.put("userAgg", PianiDiQualita::getUserAgg);
		attributeSetterBiConsumers.put(
			"userAgg",
			(BiConsumer<PianiDiQualita, String>)PianiDiQualita::setUserAgg);
		attributeGetterFunctions.put("dataIns", PianiDiQualita::getDataIns);
		attributeSetterBiConsumers.put(
			"dataIns",
			(BiConsumer<PianiDiQualita, Date>)PianiDiQualita::setDataIns);
		attributeGetterFunctions.put("dataAgg", PianiDiQualita::getDataAgg);
		attributeSetterBiConsumers.put(
			"dataAgg",
			(BiConsumer<PianiDiQualita, Date>)PianiDiQualita::setDataAgg);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId_PianiDiQualita() {
		return _Id_PianiDiQualita;
	}

	@Override
	public void setId_PianiDiQualita(long Id_PianiDiQualita) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id_PianiDiQualita = Id_PianiDiQualita;
	}

	@Override
	public String getCodicePianoDiQualita() {
		if (_CodicePianoDiQualita == null) {
			return "";
		}
		else {
			return _CodicePianoDiQualita;
		}
	}

	@Override
	public void setCodicePianoDiQualita(String CodicePianoDiQualita) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CodicePianoDiQualita = CodicePianoDiQualita;
	}

	@Override
	public long getFK_documenti() {
		return _FK_documenti;
	}

	@Override
	public void setFK_documenti(long FK_documenti) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_documenti = FK_documenti;
	}

	@Override
	public long getFK_accordoQuadro() {
		return _FK_accordoQuadro;
	}

	@Override
	public void setFK_accordoQuadro(long FK_accordoQuadro) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_accordoQuadro = FK_accordoQuadro;
	}

	@Override
	public String getDescrizione() {
		if (_Descrizione == null) {
			return "";
		}
		else {
			return _Descrizione;
		}
	}

	@Override
	public void setDescrizione(String Descrizione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Descrizione = Descrizione;
	}

	@Override
	public Date getDataInizioPiano() {
		return _DataInizioPiano;
	}

	@Override
	public void setDataInizioPiano(Date DataInizioPiano) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataInizioPiano = DataInizioPiano;
	}

	@Override
	public Date getDataFinePiano() {
		return _DataFinePiano;
	}

	@Override
	public void setDataFinePiano(Date DataFinePiano) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataFinePiano = DataFinePiano;
	}

	@Override
	public String getUserIns() {
		if (_userIns == null) {
			return "";
		}
		else {
			return _userIns;
		}
	}

	@Override
	public void setUserIns(String userIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userIns = userIns;
	}

	@Override
	public String getUserAgg() {
		if (_userAgg == null) {
			return "";
		}
		else {
			return _userAgg;
		}
	}

	@Override
	public void setUserAgg(String userAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userAgg = userAgg;
	}

	@Override
	public Date getDataIns() {
		return _dataIns;
	}

	@Override
	public void setDataIns(Date dataIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataIns = dataIns;
	}

	@Override
	public Date getDataAgg() {
		return _dataAgg;
	}

	@Override
	public void setDataAgg(Date dataAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataAgg = dataAgg;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, PianiDiQualita.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public PianiDiQualita toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, PianiDiQualita>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		PianiDiQualitaImpl pianiDiQualitaImpl = new PianiDiQualitaImpl();

		pianiDiQualitaImpl.setId_PianiDiQualita(getId_PianiDiQualita());
		pianiDiQualitaImpl.setCodicePianoDiQualita(getCodicePianoDiQualita());
		pianiDiQualitaImpl.setFK_documenti(getFK_documenti());
		pianiDiQualitaImpl.setFK_accordoQuadro(getFK_accordoQuadro());
		pianiDiQualitaImpl.setDescrizione(getDescrizione());
		pianiDiQualitaImpl.setDataInizioPiano(getDataInizioPiano());
		pianiDiQualitaImpl.setDataFinePiano(getDataFinePiano());
		pianiDiQualitaImpl.setUserIns(getUserIns());
		pianiDiQualitaImpl.setUserAgg(getUserAgg());
		pianiDiQualitaImpl.setDataIns(getDataIns());
		pianiDiQualitaImpl.setDataAgg(getDataAgg());

		pianiDiQualitaImpl.resetOriginalValues();

		return pianiDiQualitaImpl;
	}

	@Override
	public PianiDiQualita cloneWithOriginalValues() {
		PianiDiQualitaImpl pianiDiQualitaImpl = new PianiDiQualitaImpl();

		pianiDiQualitaImpl.setId_PianiDiQualita(
			this.<Long>getColumnOriginalValue("Id_PianiDiQualita"));
		pianiDiQualitaImpl.setCodicePianoDiQualita(
			this.<String>getColumnOriginalValue("CodicePianoDiQualita"));
		pianiDiQualitaImpl.setFK_documenti(
			this.<Long>getColumnOriginalValue("FK_documenti"));
		pianiDiQualitaImpl.setFK_accordoQuadro(
			this.<Long>getColumnOriginalValue("FK_accordoQuadro"));
		pianiDiQualitaImpl.setDescrizione(
			this.<String>getColumnOriginalValue("Descrizione"));
		pianiDiQualitaImpl.setDataInizioPiano(
			this.<Date>getColumnOriginalValue("DataInizioPiano"));
		pianiDiQualitaImpl.setDataFinePiano(
			this.<Date>getColumnOriginalValue("DataFinePiano"));
		pianiDiQualitaImpl.setUserIns(
			this.<String>getColumnOriginalValue("userIns"));
		pianiDiQualitaImpl.setUserAgg(
			this.<String>getColumnOriginalValue("userAgg"));
		pianiDiQualitaImpl.setDataIns(
			this.<Date>getColumnOriginalValue("dataIns"));
		pianiDiQualitaImpl.setDataAgg(
			this.<Date>getColumnOriginalValue("dataAgg"));

		return pianiDiQualitaImpl;
	}

	@Override
	public int compareTo(PianiDiQualita pianiDiQualita) {
		long primaryKey = pianiDiQualita.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof PianiDiQualita)) {
			return false;
		}

		PianiDiQualita pianiDiQualita = (PianiDiQualita)object;

		long primaryKey = pianiDiQualita.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<PianiDiQualita> toCacheModel() {
		PianiDiQualitaCacheModel pianiDiQualitaCacheModel =
			new PianiDiQualitaCacheModel();

		pianiDiQualitaCacheModel.Id_PianiDiQualita = getId_PianiDiQualita();

		pianiDiQualitaCacheModel.CodicePianoDiQualita =
			getCodicePianoDiQualita();

		String CodicePianoDiQualita =
			pianiDiQualitaCacheModel.CodicePianoDiQualita;

		if ((CodicePianoDiQualita != null) &&
			(CodicePianoDiQualita.length() == 0)) {

			pianiDiQualitaCacheModel.CodicePianoDiQualita = null;
		}

		pianiDiQualitaCacheModel.FK_documenti = getFK_documenti();

		pianiDiQualitaCacheModel.FK_accordoQuadro = getFK_accordoQuadro();

		pianiDiQualitaCacheModel.Descrizione = getDescrizione();

		String Descrizione = pianiDiQualitaCacheModel.Descrizione;

		if ((Descrizione != null) && (Descrizione.length() == 0)) {
			pianiDiQualitaCacheModel.Descrizione = null;
		}

		Date DataInizioPiano = getDataInizioPiano();

		if (DataInizioPiano != null) {
			pianiDiQualitaCacheModel.DataInizioPiano =
				DataInizioPiano.getTime();
		}
		else {
			pianiDiQualitaCacheModel.DataInizioPiano = Long.MIN_VALUE;
		}

		Date DataFinePiano = getDataFinePiano();

		if (DataFinePiano != null) {
			pianiDiQualitaCacheModel.DataFinePiano = DataFinePiano.getTime();
		}
		else {
			pianiDiQualitaCacheModel.DataFinePiano = Long.MIN_VALUE;
		}

		pianiDiQualitaCacheModel.userIns = getUserIns();

		String userIns = pianiDiQualitaCacheModel.userIns;

		if ((userIns != null) && (userIns.length() == 0)) {
			pianiDiQualitaCacheModel.userIns = null;
		}

		pianiDiQualitaCacheModel.userAgg = getUserAgg();

		String userAgg = pianiDiQualitaCacheModel.userAgg;

		if ((userAgg != null) && (userAgg.length() == 0)) {
			pianiDiQualitaCacheModel.userAgg = null;
		}

		Date dataIns = getDataIns();

		if (dataIns != null) {
			pianiDiQualitaCacheModel.dataIns = dataIns.getTime();
		}
		else {
			pianiDiQualitaCacheModel.dataIns = Long.MIN_VALUE;
		}

		Date dataAgg = getDataAgg();

		if (dataAgg != null) {
			pianiDiQualitaCacheModel.dataAgg = dataAgg.getTime();
		}
		else {
			pianiDiQualitaCacheModel.dataAgg = Long.MIN_VALUE;
		}

		return pianiDiQualitaCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<PianiDiQualita, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<PianiDiQualita, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PianiDiQualita, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply((PianiDiQualita)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<PianiDiQualita, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<PianiDiQualita, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<PianiDiQualita, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((PianiDiQualita)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, PianiDiQualita>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					PianiDiQualita.class, ModelWrapper.class);

	}

	private long _Id_PianiDiQualita;
	private String _CodicePianoDiQualita;
	private long _FK_documenti;
	private long _FK_accordoQuadro;
	private String _Descrizione;
	private Date _DataInizioPiano;
	private Date _DataFinePiano;
	private String _userIns;
	private String _userAgg;
	private Date _dataIns;
	private Date _dataAgg;

	public <T> T getColumnValue(String columnName) {
		Function<PianiDiQualita, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((PianiDiQualita)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put("Id_PianiDiQualita", _Id_PianiDiQualita);
		_columnOriginalValues.put(
			"CodicePianoDiQualita", _CodicePianoDiQualita);
		_columnOriginalValues.put("FK_documenti", _FK_documenti);
		_columnOriginalValues.put("FK_accordoQuadro", _FK_accordoQuadro);
		_columnOriginalValues.put("Descrizione", _Descrizione);
		_columnOriginalValues.put("DataInizioPiano", _DataInizioPiano);
		_columnOriginalValues.put("DataFinePiano", _DataFinePiano);
		_columnOriginalValues.put("userIns", _userIns);
		_columnOriginalValues.put("userAgg", _userAgg);
		_columnOriginalValues.put("dataIns", _dataIns);
		_columnOriginalValues.put("dataAgg", _dataAgg);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id_PianiDiQualita", 1L);

		columnBitmasks.put("CodicePianoDiQualita", 2L);

		columnBitmasks.put("FK_documenti", 4L);

		columnBitmasks.put("FK_accordoQuadro", 8L);

		columnBitmasks.put("Descrizione", 16L);

		columnBitmasks.put("DataInizioPiano", 32L);

		columnBitmasks.put("DataFinePiano", 64L);

		columnBitmasks.put("userIns", 128L);

		columnBitmasks.put("userAgg", 256L);

		columnBitmasks.put("dataIns", 512L);

		columnBitmasks.put("dataAgg", 1024L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private PianiDiQualita _escapedModel;

}