/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package servicebuilder.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringUtil;

import java.io.Serializable;

import java.lang.reflect.InvocationHandler;

import java.sql.Blob;
import java.sql.Types;

import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;
import java.util.Objects;
import java.util.function.BiConsumer;
import java.util.function.Function;

import servicebuilder.model.ProgettiFabbisogni;
import servicebuilder.model.ProgettiFabbisogniModel;

/**
 * The base model implementation for the ProgettiFabbisogni service. Represents a row in the &quot;AQ_ProgettiFabbisogni&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>ProgettiFabbisogniModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link ProgettiFabbisogniImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProgettiFabbisogniImpl
 * @generated
 */
public class ProgettiFabbisogniModelImpl
	extends BaseModelImpl<ProgettiFabbisogni>
	implements ProgettiFabbisogniModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a progetti fabbisogni model instance should use the <code>ProgettiFabbisogni</code> interface instead.
	 */
	public static final String TABLE_NAME = "AQ_ProgettiFabbisogni";

	public static final Object[][] TABLE_COLUMNS = {
		{"Id_ProgettiFabbisogni", Types.BIGINT},
		{"CodiceFabbisogni", Types.VARCHAR}, {"FK_documenti", Types.BIGINT},
		{"FK_progettiFabbisogni", Types.BIGINT},
		{"FK_pianiFabbisogni", Types.BIGINT}, {"Stato", Types.VARCHAR},
		{"DataStato", Types.TIMESTAMP}, {"Descrizione", Types.VARCHAR},
		{"DataScadenza", Types.TIMESTAMP}, {"ImportoComplessivo", Types.DOUBLE},
		{"DataInizioPiano", Types.TIMESTAMP},
		{"DataFinePiano", Types.TIMESTAMP}, {"userIns", Types.VARCHAR},
		{"userAgg", Types.VARCHAR}, {"dataIns", Types.TIMESTAMP},
		{"dataAgg", Types.TIMESTAMP}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("Id_ProgettiFabbisogni", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("CodiceFabbisogni", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("FK_documenti", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FK_progettiFabbisogni", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("FK_pianiFabbisogni", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("Stato", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DataStato", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("Descrizione", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("DataScadenza", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("ImportoComplessivo", Types.DOUBLE);
		TABLE_COLUMNS_MAP.put("DataInizioPiano", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("DataFinePiano", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("userIns", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("userAgg", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("dataIns", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("dataAgg", Types.TIMESTAMP);
	}

	public static final String TABLE_SQL_CREATE =
		"create table AQ_ProgettiFabbisogni (Id_ProgettiFabbisogni LONG not null primary key,CodiceFabbisogni VARCHAR(75) null,FK_documenti LONG,FK_progettiFabbisogni LONG,FK_pianiFabbisogni LONG,Stato VARCHAR(75) null,DataStato DATE null,Descrizione VARCHAR(75) null,DataScadenza DATE null,ImportoComplessivo DOUBLE,DataInizioPiano DATE null,DataFinePiano DATE null,userIns VARCHAR(75) null,userAgg VARCHAR(75) null,dataIns DATE null,dataAgg DATE null)";

	public static final String TABLE_SQL_DROP =
		"drop table AQ_ProgettiFabbisogni";

	public static final String ORDER_BY_JPQL =
		" ORDER BY progettiFabbisogni.Id_ProgettiFabbisogni ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY AQ_ProgettiFabbisogni.Id_ProgettiFabbisogni ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link #getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long FK_PIANIFABBISOGNI_COLUMN_BITMASK = 1L;

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *		#getColumnBitmask(String)}
	 */
	@Deprecated
	public static final long ID_PROGETTIFABBISOGNI_COLUMN_BITMASK = 2L;

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
	}

	public ProgettiFabbisogniModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _Id_ProgettiFabbisogni;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setId_ProgettiFabbisogni(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _Id_ProgettiFabbisogni;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return ProgettiFabbisogni.class;
	}

	@Override
	public String getModelClassName() {
		return ProgettiFabbisogni.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<ProgettiFabbisogni, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		for (Map.Entry<String, Function<ProgettiFabbisogni, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProgettiFabbisogni, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName,
				attributeGetterFunction.apply((ProgettiFabbisogni)this));
		}

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<ProgettiFabbisogni, Object>>
			attributeSetterBiConsumers = getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<ProgettiFabbisogni, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(ProgettiFabbisogni)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<ProgettiFabbisogni, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<ProgettiFabbisogni, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static final Map<String, Function<ProgettiFabbisogni, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<ProgettiFabbisogni, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<ProgettiFabbisogni, Object>>
			attributeGetterFunctions =
				new LinkedHashMap
					<String, Function<ProgettiFabbisogni, Object>>();
		Map<String, BiConsumer<ProgettiFabbisogni, ?>>
			attributeSetterBiConsumers =
				new LinkedHashMap<String, BiConsumer<ProgettiFabbisogni, ?>>();

		attributeGetterFunctions.put(
			"Id_ProgettiFabbisogni",
			ProgettiFabbisogni::getId_ProgettiFabbisogni);
		attributeSetterBiConsumers.put(
			"Id_ProgettiFabbisogni",
			(BiConsumer<ProgettiFabbisogni, Long>)
				ProgettiFabbisogni::setId_ProgettiFabbisogni);
		attributeGetterFunctions.put(
			"CodiceFabbisogni", ProgettiFabbisogni::getCodiceFabbisogni);
		attributeSetterBiConsumers.put(
			"CodiceFabbisogni",
			(BiConsumer<ProgettiFabbisogni, String>)
				ProgettiFabbisogni::setCodiceFabbisogni);
		attributeGetterFunctions.put(
			"FK_documenti", ProgettiFabbisogni::getFK_documenti);
		attributeSetterBiConsumers.put(
			"FK_documenti",
			(BiConsumer<ProgettiFabbisogni, Long>)
				ProgettiFabbisogni::setFK_documenti);
		attributeGetterFunctions.put(
			"FK_progettiFabbisogni",
			ProgettiFabbisogni::getFK_progettiFabbisogni);
		attributeSetterBiConsumers.put(
			"FK_progettiFabbisogni",
			(BiConsumer<ProgettiFabbisogni, Long>)
				ProgettiFabbisogni::setFK_progettiFabbisogni);
		attributeGetterFunctions.put(
			"FK_pianiFabbisogni", ProgettiFabbisogni::getFK_pianiFabbisogni);
		attributeSetterBiConsumers.put(
			"FK_pianiFabbisogni",
			(BiConsumer<ProgettiFabbisogni, Long>)
				ProgettiFabbisogni::setFK_pianiFabbisogni);
		attributeGetterFunctions.put("Stato", ProgettiFabbisogni::getStato);
		attributeSetterBiConsumers.put(
			"Stato",
			(BiConsumer<ProgettiFabbisogni, String>)
				ProgettiFabbisogni::setStato);
		attributeGetterFunctions.put(
			"DataStato", ProgettiFabbisogni::getDataStato);
		attributeSetterBiConsumers.put(
			"DataStato",
			(BiConsumer<ProgettiFabbisogni, Date>)
				ProgettiFabbisogni::setDataStato);
		attributeGetterFunctions.put(
			"Descrizione", ProgettiFabbisogni::getDescrizione);
		attributeSetterBiConsumers.put(
			"Descrizione",
			(BiConsumer<ProgettiFabbisogni, String>)
				ProgettiFabbisogni::setDescrizione);
		attributeGetterFunctions.put(
			"DataScadenza", ProgettiFabbisogni::getDataScadenza);
		attributeSetterBiConsumers.put(
			"DataScadenza",
			(BiConsumer<ProgettiFabbisogni, Date>)
				ProgettiFabbisogni::setDataScadenza);
		attributeGetterFunctions.put(
			"ImportoComplessivo", ProgettiFabbisogni::getImportoComplessivo);
		attributeSetterBiConsumers.put(
			"ImportoComplessivo",
			(BiConsumer<ProgettiFabbisogni, Double>)
				ProgettiFabbisogni::setImportoComplessivo);
		attributeGetterFunctions.put(
			"DataInizioPiano", ProgettiFabbisogni::getDataInizioPiano);
		attributeSetterBiConsumers.put(
			"DataInizioPiano",
			(BiConsumer<ProgettiFabbisogni, Date>)
				ProgettiFabbisogni::setDataInizioPiano);
		attributeGetterFunctions.put(
			"DataFinePiano", ProgettiFabbisogni::getDataFinePiano);
		attributeSetterBiConsumers.put(
			"DataFinePiano",
			(BiConsumer<ProgettiFabbisogni, Date>)
				ProgettiFabbisogni::setDataFinePiano);
		attributeGetterFunctions.put("userIns", ProgettiFabbisogni::getUserIns);
		attributeSetterBiConsumers.put(
			"userIns",
			(BiConsumer<ProgettiFabbisogni, String>)
				ProgettiFabbisogni::setUserIns);
		attributeGetterFunctions.put("userAgg", ProgettiFabbisogni::getUserAgg);
		attributeSetterBiConsumers.put(
			"userAgg",
			(BiConsumer<ProgettiFabbisogni, String>)
				ProgettiFabbisogni::setUserAgg);
		attributeGetterFunctions.put("dataIns", ProgettiFabbisogni::getDataIns);
		attributeSetterBiConsumers.put(
			"dataIns",
			(BiConsumer<ProgettiFabbisogni, Date>)
				ProgettiFabbisogni::setDataIns);
		attributeGetterFunctions.put("dataAgg", ProgettiFabbisogni::getDataAgg);
		attributeSetterBiConsumers.put(
			"dataAgg",
			(BiConsumer<ProgettiFabbisogni, Date>)
				ProgettiFabbisogni::setDataAgg);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@Override
	public long getId_ProgettiFabbisogni() {
		return _Id_ProgettiFabbisogni;
	}

	@Override
	public void setId_ProgettiFabbisogni(long Id_ProgettiFabbisogni) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Id_ProgettiFabbisogni = Id_ProgettiFabbisogni;
	}

	@Override
	public String getCodiceFabbisogni() {
		if (_CodiceFabbisogni == null) {
			return "";
		}
		else {
			return _CodiceFabbisogni;
		}
	}

	@Override
	public void setCodiceFabbisogni(String CodiceFabbisogni) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_CodiceFabbisogni = CodiceFabbisogni;
	}

	@Override
	public long getFK_documenti() {
		return _FK_documenti;
	}

	@Override
	public void setFK_documenti(long FK_documenti) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_documenti = FK_documenti;
	}

	@Override
	public long getFK_progettiFabbisogni() {
		return _FK_progettiFabbisogni;
	}

	@Override
	public void setFK_progettiFabbisogni(long FK_progettiFabbisogni) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_progettiFabbisogni = FK_progettiFabbisogni;
	}

	@Override
	public long getFK_pianiFabbisogni() {
		return _FK_pianiFabbisogni;
	}

	@Override
	public void setFK_pianiFabbisogni(long FK_pianiFabbisogni) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_FK_pianiFabbisogni = FK_pianiFabbisogni;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), replaced by {@link
	 *             #getColumnOriginalValue(String)}
	 */
	@Deprecated
	public long getOriginalFK_pianiFabbisogni() {
		return GetterUtil.getLong(
			this.<Long>getColumnOriginalValue("FK_pianiFabbisogni"));
	}

	@Override
	public String getStato() {
		if (_Stato == null) {
			return "";
		}
		else {
			return _Stato;
		}
	}

	@Override
	public void setStato(String Stato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Stato = Stato;
	}

	@Override
	public Date getDataStato() {
		return _DataStato;
	}

	@Override
	public void setDataStato(Date DataStato) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataStato = DataStato;
	}

	@Override
	public String getDescrizione() {
		if (_Descrizione == null) {
			return "";
		}
		else {
			return _Descrizione;
		}
	}

	@Override
	public void setDescrizione(String Descrizione) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_Descrizione = Descrizione;
	}

	@Override
	public Date getDataScadenza() {
		return _DataScadenza;
	}

	@Override
	public void setDataScadenza(Date DataScadenza) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataScadenza = DataScadenza;
	}

	@Override
	public Double getImportoComplessivo() {
		return _ImportoComplessivo;
	}

	@Override
	public void setImportoComplessivo(Double ImportoComplessivo) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_ImportoComplessivo = ImportoComplessivo;
	}

	@Override
	public Date getDataInizioPiano() {
		return _DataInizioPiano;
	}

	@Override
	public void setDataInizioPiano(Date DataInizioPiano) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataInizioPiano = DataInizioPiano;
	}

	@Override
	public Date getDataFinePiano() {
		return _DataFinePiano;
	}

	@Override
	public void setDataFinePiano(Date DataFinePiano) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_DataFinePiano = DataFinePiano;
	}

	@Override
	public String getUserIns() {
		if (_userIns == null) {
			return "";
		}
		else {
			return _userIns;
		}
	}

	@Override
	public void setUserIns(String userIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userIns = userIns;
	}

	@Override
	public String getUserAgg() {
		if (_userAgg == null) {
			return "";
		}
		else {
			return _userAgg;
		}
	}

	@Override
	public void setUserAgg(String userAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_userAgg = userAgg;
	}

	@Override
	public Date getDataIns() {
		return _dataIns;
	}

	@Override
	public void setDataIns(Date dataIns) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataIns = dataIns;
	}

	@Override
	public Date getDataAgg() {
		return _dataAgg;
	}

	@Override
	public void setDataAgg(Date dataAgg) {
		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		_dataAgg = dataAgg;
	}

	public long getColumnBitmask() {
		if (_columnBitmask > 0) {
			return _columnBitmask;
		}

		if ((_columnOriginalValues == null) ||
			(_columnOriginalValues == Collections.EMPTY_MAP)) {

			return 0;
		}

		for (Map.Entry<String, Object> entry :
				_columnOriginalValues.entrySet()) {

			if (!Objects.equals(
					entry.getValue(), getColumnValue(entry.getKey()))) {

				_columnBitmask |= _columnBitmasks.get(entry.getKey());
			}
		}

		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			0, ProgettiFabbisogni.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public ProgettiFabbisogni toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, ProgettiFabbisogni>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		ProgettiFabbisogniImpl progettiFabbisogniImpl =
			new ProgettiFabbisogniImpl();

		progettiFabbisogniImpl.setId_ProgettiFabbisogni(
			getId_ProgettiFabbisogni());
		progettiFabbisogniImpl.setCodiceFabbisogni(getCodiceFabbisogni());
		progettiFabbisogniImpl.setFK_documenti(getFK_documenti());
		progettiFabbisogniImpl.setFK_progettiFabbisogni(
			getFK_progettiFabbisogni());
		progettiFabbisogniImpl.setFK_pianiFabbisogni(getFK_pianiFabbisogni());
		progettiFabbisogniImpl.setStato(getStato());
		progettiFabbisogniImpl.setDataStato(getDataStato());
		progettiFabbisogniImpl.setDescrizione(getDescrizione());
		progettiFabbisogniImpl.setDataScadenza(getDataScadenza());
		progettiFabbisogniImpl.setImportoComplessivo(getImportoComplessivo());
		progettiFabbisogniImpl.setDataInizioPiano(getDataInizioPiano());
		progettiFabbisogniImpl.setDataFinePiano(getDataFinePiano());
		progettiFabbisogniImpl.setUserIns(getUserIns());
		progettiFabbisogniImpl.setUserAgg(getUserAgg());
		progettiFabbisogniImpl.setDataIns(getDataIns());
		progettiFabbisogniImpl.setDataAgg(getDataAgg());

		progettiFabbisogniImpl.resetOriginalValues();

		return progettiFabbisogniImpl;
	}

	@Override
	public ProgettiFabbisogni cloneWithOriginalValues() {
		ProgettiFabbisogniImpl progettiFabbisogniImpl =
			new ProgettiFabbisogniImpl();

		progettiFabbisogniImpl.setId_ProgettiFabbisogni(
			this.<Long>getColumnOriginalValue("Id_ProgettiFabbisogni"));
		progettiFabbisogniImpl.setCodiceFabbisogni(
			this.<String>getColumnOriginalValue("CodiceFabbisogni"));
		progettiFabbisogniImpl.setFK_documenti(
			this.<Long>getColumnOriginalValue("FK_documenti"));
		progettiFabbisogniImpl.setFK_progettiFabbisogni(
			this.<Long>getColumnOriginalValue("FK_progettiFabbisogni"));
		progettiFabbisogniImpl.setFK_pianiFabbisogni(
			this.<Long>getColumnOriginalValue("FK_pianiFabbisogni"));
		progettiFabbisogniImpl.setStato(
			this.<String>getColumnOriginalValue("Stato"));
		progettiFabbisogniImpl.setDataStato(
			this.<Date>getColumnOriginalValue("DataStato"));
		progettiFabbisogniImpl.setDescrizione(
			this.<String>getColumnOriginalValue("Descrizione"));
		progettiFabbisogniImpl.setDataScadenza(
			this.<Date>getColumnOriginalValue("DataScadenza"));
		progettiFabbisogniImpl.setImportoComplessivo(
			this.<Double>getColumnOriginalValue("ImportoComplessivo"));
		progettiFabbisogniImpl.setDataInizioPiano(
			this.<Date>getColumnOriginalValue("DataInizioPiano"));
		progettiFabbisogniImpl.setDataFinePiano(
			this.<Date>getColumnOriginalValue("DataFinePiano"));
		progettiFabbisogniImpl.setUserIns(
			this.<String>getColumnOriginalValue("userIns"));
		progettiFabbisogniImpl.setUserAgg(
			this.<String>getColumnOriginalValue("userAgg"));
		progettiFabbisogniImpl.setDataIns(
			this.<Date>getColumnOriginalValue("dataIns"));
		progettiFabbisogniImpl.setDataAgg(
			this.<Date>getColumnOriginalValue("dataAgg"));

		return progettiFabbisogniImpl;
	}

	@Override
	public int compareTo(ProgettiFabbisogni progettiFabbisogni) {
		long primaryKey = progettiFabbisogni.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object object) {
		if (this == object) {
			return true;
		}

		if (!(object instanceof ProgettiFabbisogni)) {
			return false;
		}

		ProgettiFabbisogni progettiFabbisogni = (ProgettiFabbisogni)object;

		long primaryKey = progettiFabbisogni.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isEntityCacheEnabled() {
		return true;
	}

	/**
	 * @deprecated As of Athanasius (7.3.x), with no direct replacement
	 */
	@Deprecated
	@Override
	public boolean isFinderCacheEnabled() {
		return true;
	}

	@Override
	public void resetOriginalValues() {
		_columnOriginalValues = Collections.emptyMap();

		_columnBitmask = 0;
	}

	@Override
	public CacheModel<ProgettiFabbisogni> toCacheModel() {
		ProgettiFabbisogniCacheModel progettiFabbisogniCacheModel =
			new ProgettiFabbisogniCacheModel();

		progettiFabbisogniCacheModel.Id_ProgettiFabbisogni =
			getId_ProgettiFabbisogni();

		progettiFabbisogniCacheModel.CodiceFabbisogni = getCodiceFabbisogni();

		String CodiceFabbisogni = progettiFabbisogniCacheModel.CodiceFabbisogni;

		if ((CodiceFabbisogni != null) && (CodiceFabbisogni.length() == 0)) {
			progettiFabbisogniCacheModel.CodiceFabbisogni = null;
		}

		progettiFabbisogniCacheModel.FK_documenti = getFK_documenti();

		progettiFabbisogniCacheModel.FK_progettiFabbisogni =
			getFK_progettiFabbisogni();

		progettiFabbisogniCacheModel.FK_pianiFabbisogni =
			getFK_pianiFabbisogni();

		progettiFabbisogniCacheModel.Stato = getStato();

		String Stato = progettiFabbisogniCacheModel.Stato;

		if ((Stato != null) && (Stato.length() == 0)) {
			progettiFabbisogniCacheModel.Stato = null;
		}

		Date DataStato = getDataStato();

		if (DataStato != null) {
			progettiFabbisogniCacheModel.DataStato = DataStato.getTime();
		}
		else {
			progettiFabbisogniCacheModel.DataStato = Long.MIN_VALUE;
		}

		progettiFabbisogniCacheModel.Descrizione = getDescrizione();

		String Descrizione = progettiFabbisogniCacheModel.Descrizione;

		if ((Descrizione != null) && (Descrizione.length() == 0)) {
			progettiFabbisogniCacheModel.Descrizione = null;
		}

		Date DataScadenza = getDataScadenza();

		if (DataScadenza != null) {
			progettiFabbisogniCacheModel.DataScadenza = DataScadenza.getTime();
		}
		else {
			progettiFabbisogniCacheModel.DataScadenza = Long.MIN_VALUE;
		}

		Double ImportoComplessivo = getImportoComplessivo();

		if (ImportoComplessivo != null) {
			progettiFabbisogniCacheModel.ImportoComplessivo =
				ImportoComplessivo;
		}

		Date DataInizioPiano = getDataInizioPiano();

		if (DataInizioPiano != null) {
			progettiFabbisogniCacheModel.DataInizioPiano =
				DataInizioPiano.getTime();
		}
		else {
			progettiFabbisogniCacheModel.DataInizioPiano = Long.MIN_VALUE;
		}

		Date DataFinePiano = getDataFinePiano();

		if (DataFinePiano != null) {
			progettiFabbisogniCacheModel.DataFinePiano =
				DataFinePiano.getTime();
		}
		else {
			progettiFabbisogniCacheModel.DataFinePiano = Long.MIN_VALUE;
		}

		progettiFabbisogniCacheModel.userIns = getUserIns();

		String userIns = progettiFabbisogniCacheModel.userIns;

		if ((userIns != null) && (userIns.length() == 0)) {
			progettiFabbisogniCacheModel.userIns = null;
		}

		progettiFabbisogniCacheModel.userAgg = getUserAgg();

		String userAgg = progettiFabbisogniCacheModel.userAgg;

		if ((userAgg != null) && (userAgg.length() == 0)) {
			progettiFabbisogniCacheModel.userAgg = null;
		}

		Date dataIns = getDataIns();

		if (dataIns != null) {
			progettiFabbisogniCacheModel.dataIns = dataIns.getTime();
		}
		else {
			progettiFabbisogniCacheModel.dataIns = Long.MIN_VALUE;
		}

		Date dataAgg = getDataAgg();

		if (dataAgg != null) {
			progettiFabbisogniCacheModel.dataAgg = dataAgg.getTime();
		}
		else {
			progettiFabbisogniCacheModel.dataAgg = Long.MIN_VALUE;
		}

		return progettiFabbisogniCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<ProgettiFabbisogni, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 2);

		sb.append("{");

		for (Map.Entry<String, Function<ProgettiFabbisogni, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProgettiFabbisogni, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("\"");
			sb.append(attributeName);
			sb.append("\": ");

			Object value = attributeGetterFunction.apply(
				(ProgettiFabbisogni)this);

			if (value == null) {
				sb.append("null");
			}
			else if (value instanceof Blob || value instanceof Date ||
					 value instanceof Map || value instanceof String) {

				sb.append(
					"\"" + StringUtil.replace(value.toString(), "\"", "'") +
						"\"");
			}
			else {
				sb.append(value);
			}

			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<ProgettiFabbisogni, Object>>
			attributeGetterFunctions = getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			(5 * attributeGetterFunctions.size()) + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<ProgettiFabbisogni, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<ProgettiFabbisogni, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((ProgettiFabbisogni)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, ProgettiFabbisogni>
			_escapedModelProxyProviderFunction =
				ProxyUtil.getProxyProviderFunction(
					ProgettiFabbisogni.class, ModelWrapper.class);

	}

	private long _Id_ProgettiFabbisogni;
	private String _CodiceFabbisogni;
	private long _FK_documenti;
	private long _FK_progettiFabbisogni;
	private long _FK_pianiFabbisogni;
	private String _Stato;
	private Date _DataStato;
	private String _Descrizione;
	private Date _DataScadenza;
	private Double _ImportoComplessivo;
	private Date _DataInizioPiano;
	private Date _DataFinePiano;
	private String _userIns;
	private String _userAgg;
	private Date _dataIns;
	private Date _dataAgg;

	public <T> T getColumnValue(String columnName) {
		Function<ProgettiFabbisogni, Object> function =
			_attributeGetterFunctions.get(columnName);

		if (function == null) {
			throw new IllegalArgumentException(
				"No attribute getter function found for " + columnName);
		}

		return (T)function.apply((ProgettiFabbisogni)this);
	}

	public <T> T getColumnOriginalValue(String columnName) {
		if (_columnOriginalValues == null) {
			return null;
		}

		if (_columnOriginalValues == Collections.EMPTY_MAP) {
			_setColumnOriginalValues();
		}

		return (T)_columnOriginalValues.get(columnName);
	}

	private void _setColumnOriginalValues() {
		_columnOriginalValues = new HashMap<String, Object>();

		_columnOriginalValues.put(
			"Id_ProgettiFabbisogni", _Id_ProgettiFabbisogni);
		_columnOriginalValues.put("CodiceFabbisogni", _CodiceFabbisogni);
		_columnOriginalValues.put("FK_documenti", _FK_documenti);
		_columnOriginalValues.put(
			"FK_progettiFabbisogni", _FK_progettiFabbisogni);
		_columnOriginalValues.put("FK_pianiFabbisogni", _FK_pianiFabbisogni);
		_columnOriginalValues.put("Stato", _Stato);
		_columnOriginalValues.put("DataStato", _DataStato);
		_columnOriginalValues.put("Descrizione", _Descrizione);
		_columnOriginalValues.put("DataScadenza", _DataScadenza);
		_columnOriginalValues.put("ImportoComplessivo", _ImportoComplessivo);
		_columnOriginalValues.put("DataInizioPiano", _DataInizioPiano);
		_columnOriginalValues.put("DataFinePiano", _DataFinePiano);
		_columnOriginalValues.put("userIns", _userIns);
		_columnOriginalValues.put("userAgg", _userAgg);
		_columnOriginalValues.put("dataIns", _dataIns);
		_columnOriginalValues.put("dataAgg", _dataAgg);
	}

	private transient Map<String, Object> _columnOriginalValues;

	public static long getColumnBitmask(String columnName) {
		return _columnBitmasks.get(columnName);
	}

	private static final Map<String, Long> _columnBitmasks;

	static {
		Map<String, Long> columnBitmasks = new HashMap<>();

		columnBitmasks.put("Id_ProgettiFabbisogni", 1L);

		columnBitmasks.put("CodiceFabbisogni", 2L);

		columnBitmasks.put("FK_documenti", 4L);

		columnBitmasks.put("FK_progettiFabbisogni", 8L);

		columnBitmasks.put("FK_pianiFabbisogni", 16L);

		columnBitmasks.put("Stato", 32L);

		columnBitmasks.put("DataStato", 64L);

		columnBitmasks.put("Descrizione", 128L);

		columnBitmasks.put("DataScadenza", 256L);

		columnBitmasks.put("ImportoComplessivo", 512L);

		columnBitmasks.put("DataInizioPiano", 1024L);

		columnBitmasks.put("DataFinePiano", 2048L);

		columnBitmasks.put("userIns", 4096L);

		columnBitmasks.put("userAgg", 8192L);

		columnBitmasks.put("dataIns", 16384L);

		columnBitmasks.put("dataAgg", 32768L);

		_columnBitmasks = Collections.unmodifiableMap(columnBitmasks);
	}

	private long _columnBitmask;
	private ProgettiFabbisogni _escapedModel;

}